pragma ComponentBehavior: Bound
// ----------------------------------------------------------------------------
// pill.qml — GENERATED by tangling qs-pill-docs.org. Edit the .org, not this.
// A morphing "pill" overlay for KDE Plasma 6 / KWin / Wayland.
//
// v1 scope (all proven to work on this machine):
//   * a layer-shell window pinned top-center, ALWAYS on top, reserving NO space
//   * collapsed: shows the clock
//   * hovered:   morphs wider/taller and reveals:
//       - virtual-desktop dots on the top-left (real KWin desktops, click to switch)
//       - volume + battery on the top-right (native Quickshell services)
//       - the system tray on a second row
//   * clicks pass THROUGH the transparent area around the pill (input mask)
//
// Deferred (need a KWin-script bridge — see the .org capability table):
//   * taskbar of open windows / pinned apps
//   * hide-when-a-fullscreen-window-is-focused
//   * notification takeover (would require disabling Plasma's notifier)
//
// Run with:   qs -p quickshell/pill.qml      (from the repo root)
// ----------------------------------------------------------------------------
import QtQuick
import Quickshell
import Quickshell.Wayland
import Quickshell.Io
import Quickshell.Services.SystemTray
import Quickshell.Services.Pipewire
import Quickshell.Services.UPower

ShellRoot {
    id: root
    // -- Shared state for the KWin virtual desktops, filled in over DBus below.
    // desktops: array of { id: string, name: string }   current: string (id)
    property var desktops: []
    property string currentDesktop: ""

    // ---- KWin virtual desktops via DBus (org.kde.KWin /VirtualDesktopManager) ----
    // Quickshell has no native KWin-desktop binding and KWin does not expose the
    // ext-workspace protocol, so we talk to KWin's documented DBus interface
    // through `gdbus`. This is the supported path for KWin, not guesswork.

    // 1) Fetch the desktop list once at startup (and whenever it changes).
    Process {
        id: fetchDesktops
        command: ["gdbus", "call", "--session", "--dest", "org.kde.KWin",
            "--object-path", "/VirtualDesktopManager", "--method",
            "org.freedesktop.DBus.Properties.Get",
            "org.kde.KWin.VirtualDesktopManager", "desktops"]
        running: true
        stdout: StdioCollector {
            onStreamFinished: {
                // text looks like: (<[(uint32 0, 'id', 'Desktop 1'), ...]>,)
                const out = [];
                const re = /\(\s*uint32\s+\d+\s*,\s*'([^']*)'\s*,\s*'([^']*)'\s*\)/g;
                let m;
                while ((m = re.exec(this.text)) !== null)
                    out.push({ id: m[1], name: m[2] });
                root.desktops = out;
            }
        }
    }

    // 2) Fetch which desktop is current (and refresh on the signal below).
    Process {
        id: fetchCurrent
        command: ["gdbus", "call", "--session", "--dest", "org.kde.KWin",
            "--object-path", "/VirtualDesktopManager", "--method",
            "org.freedesktop.DBus.Properties.Get",
            "org.kde.KWin.VirtualDesktopManager", "current"]
        running: true
        stdout: StdioCollector {
            onStreamFinished: {
                const m = this.text.match(/'([^']*)'/);
                if (m) root.currentDesktop = m[1];
            }
        }
    }

    // 3) Listen for KWin's currentChanged signal so the dots stay live without polling.
    Process {
        running: true
        command: ["gdbus", "monitor", "--session", "--dest", "org.kde.KWin",
            "--object-path", "/VirtualDesktopManager"]
        stdout: SplitParser {
            onRead: line => {
                if (line.indexOf("currentChanged") !== -1) {
                    const m = line.match(/'([^']*)'/);
                    if (m) root.currentDesktop = m[1];
                } else if (line.indexOf("desktopCreated") !== -1
                        || line.indexOf("desktopRemoved") !== -1) {
                    fetchDesktops.running = true;
                }
            }
        }
    }

    // Switch desktop by id (sets the writable `current` property over DBus).
    function switchDesktop(id) {
        switchProc.command = ["gdbus", "call", "--session", "--dest", "org.kde.KWin",
            "--object-path", "/VirtualDesktopManager", "--method",
            "org.freedesktop.DBus.Properties.Set",
            "org.kde.KWin.VirtualDesktopManager", "current",
            "<'" + id + "'>"];
        switchProc.running = true;
    }
    Process { id: switchProc }

    // Keep the default audio sink "bound" so its volume/mute stay live.
    PwObjectTracker { objects: [Pipewire.defaultAudioSink] }

    // ---- One pill per monitor ----
    Variants {
        model: Quickshell.screens

        PanelWindow {
            id: win
            required property var modelData
            screen: modelData

            // Float on top of everything, reserve no space, full-width invisible strip.
            WlrLayershell.layer: WlrLayer.Overlay
            exclusionMode: ExclusionMode.Ignore
            color: "transparent"
            anchors { top: true; left: true; right: true }
            implicitHeight: 220          // tall enough to host the expanded pill
            // Only the pill itself should catch clicks; the rest passes through.
            mask: Region { item: pill }

            property bool expanded: hover.hovered

            Item {
                id: pill
                anchors.horizontalCenter: parent.horizontalCenter
                y: 6
                width: win.expanded ? 360 : 150
                height: win.expanded ? 120 : 34
                Behavior on width  { NumberAnimation { duration: 220; easing.type: Easing.OutCubic } }
                Behavior on height { NumberAnimation { duration: 220; easing.type: Easing.OutCubic } }

                HoverHandler { id: hover }

                Rectangle {
                    anchors.fill: parent
                    radius: height / 2 > 24 ? 24 : height / 2
                    color: "#0f1115"
                    border.color: "#2a2f3a"
                    border.width: 1
                    Behavior on radius { NumberAnimation { duration: 220 } }
                }

                // ---- Collapsed content: the clock ----
                Text {
                    anchors.centerIn: parent
                    visible: !win.expanded
                    color: "#e6e6e6"
                    font.pixelSize: 15
                    font.family: "monospace"
                    text: clock.text
                }

                // ---- Expanded content ----
                Item {
                    anchors.fill: parent
                    anchors.margins: 12
                    opacity: win.expanded ? 1 : 0
                    visible: opacity > 0
                    Behavior on opacity { NumberAnimation { duration: 160 } }

                    // Top-left: virtual desktop dots (real KWin desktops).
                    Row {
                        id: vdRow
                        anchors.top: parent.top
                        anchors.left: parent.left
                        spacing: 8
                        Repeater {
                            model: root.desktops
                            delegate: Rectangle {
                                required property var modelData
                                width: 14; height: 14; radius: 7
                                color: modelData.id === root.currentDesktop ? "#7aa2f7" : "transparent"
                                border.color: "#7aa2f7"; border.width: 2
                                MouseArea {
                                    anchors.fill: parent
                                    cursorShape: Qt.PointingHandCursor
                                    onClicked: root.switchDesktop(modelData.id)
                                }
                            }
                        }
                    }

                    // Top-right: volume + battery (native services).
                    Row {
                        anchors.top: parent.top
                        anchors.right: parent.right
                        spacing: 14
                        Text {
                            color: "#e6e6e6"; font.pixelSize: 13
                            text: {
                                const s = Pipewire.defaultAudioSink;
                                if (!s || !s.audio) return "🔊 --";
                                if (s.audio.muted) return "🔇";
                                return "🔊 " + Math.round(s.audio.volume * 100) + "%";
                            }
                        }
                        Text {
                            color: "#e6e6e6"; font.pixelSize: 13
                            text: {
                                const d = UPower.displayDevice;
                                if (!d || !d.isLaptopBattery) return "";
                                return "🔋 " + Math.round(d.percentage) + "%";
                            }
                        }
                    }

                    // Second row: the system tray.
                    Row {
                        anchors.left: parent.left
                        anchors.bottom: parent.bottom
                        spacing: 10
                        Repeater {
                            model: SystemTray.items
                            delegate: Item {
                                required property SystemTrayItem modelData
                                width: 20; height: 20
                                Image {
                                    anchors.fill: parent
                                    source: modelData.icon
                                    fillMode: Image.PreserveAspectFit
                                }
                                MouseArea {
                                    anchors.fill: parent
                                    acceptedButtons: Qt.LeftButton | Qt.RightButton
                                    onClicked: mouse => {
                                        if (mouse.button === Qt.LeftButton)
                                            modelData.activate();
                                        else
                                            modelData.display(win, width / 2, height);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // Clock source, ticking every second.
    SystemClock { id: sysclock; precision: SystemClock.Seconds }
    QtObject {
        id: clock
        property string text: Qt.formatDateTime(sysclock.date, "ddd  hh:mm:ss")
    }
}
