pragma ComponentBehavior: Bound
// MockNetState.qml — stand-in for NetState.qml (screenshot harness). Exposes the
// exact surface NetworkMenu/StatusIcons read; Wi-Fi rows are real QtObjects (so the
// per-row `Connections { onConnectedChanged }` binds to a genuine signal).
import QtQuick

Item {
    id: root
    property bool wifiEnabled: true
    property var wifiDev: ({ scannerEnabled: false })
    property var nets: []
    property var lans: [{ name: "Home Ethernet", active: true }]
    property var vpns: [{ name: "Mullvad", active: false },
                        { name: "Work WireGuard", active: true }]
    property string busyConn: ""
    // aggregates read by StatusIcons
    readonly property bool wifiActive: nets.some(n => n.connected)
    readonly property real wifiSignal: { for (const n of nets) if (n.connected) return n.signalStrength; return 0; }
    readonly property bool lanActive: lans.some(l => l.active)
    readonly property bool vpnActive: vpns.some(v => v.active)
    function refresh() {}
    function setConn(name, up) {}

    component WifiNet: QtObject {
        property string name: ""
        property bool connected: false
        property real signalStrength: 0
        property int security: 0        // 0 == Open (no lock), >0 secured
        property bool known: false
        // (connectedChanged is auto-generated by the `connected` property)
        function connect() {}
        function disconnect() {}
        function connectWithPsk(t) {}
    }
    Component { id: netComp; WifiNet {} }
    Component.onCompleted: {
        const specs = [
            { name: "Broadsheet-5G",     connected: true,  signalStrength: 0.92, security: 1, known: true },
            { name: "Broadsheet",        connected: false, signalStrength: 0.66, security: 1, known: true },
            { name: "CoffeeShop Guest",  connected: false, signalStrength: 0.40, security: 0, known: false },
            { name: "NETGEAR-2.4",       connected: false, signalStrength: 0.22, security: 1, known: false }
        ];
        root.nets = specs.map(s => netComp.createObject(root, s));
    }
}
