.pragma library
// emojidata.js — bundled, categorized emoji dataset for the pill's emoji
// picker (EmojiMenu.qml). GENERATED from the iamcal emoji-datasource by a
// one-off python pass (see the emoji-picker work); do not hand-edit —
// regenerate if the emoji set needs refreshing. Each category holds rows of
// [char, name, keywords]; `name` shows in the hover tooltip, `keywords` is the
// lowercased search haystack (Unicode name + every short_name word).
var CATEGORIES = [
  {
    "name": "Smileys & Emotion",
    "label": "Smileys",
    "tab": "\ud83d\ude00",
    "emojis": [
      ["😀","grinning face","face grinning"],
      ["😃","smiling face with open mouth","face mouth open smiley smiling with"],
      ["😄","smiling face with open mouth and smiling eyes","and eyes face mouth open smile smiling with"],
      ["😁","grinning face with smiling eyes","eyes face grin grinning smiling with"],
      ["😆","smiling face with open mouth and tightly-closed eyes","and closed eyes face laughing mouth open satisfied smiling tightly with"],
      ["😅","smiling face with open mouth and cold sweat","and cold face mouth open smile smiling sweat with"],
      ["🤣","rolling on the floor laughing","floor laughing on rolling the"],
      ["😂","face with tears of joy","face joy of tears with"],
      ["🙂","slightly smiling face","face slightly smiling"],
      ["🙃","upside-down face","down face upside"],
      ["😉","winking face","face wink winking"],
      ["😊","smiling face with smiling eyes","blush eyes face smiling with"],
      ["😇","smiling face with halo","face halo innocent smiling with"],
      ["🥰","smiling face with smiling eyes and three hearts","3 and eyes face hearts smiling three with"],
      ["😍","smiling face with heart-shaped eyes","eyes face heart shaped smiling with"],
      ["🤩","grinning face with star eyes","eyes face grinning star struck with"],
      ["😘","face throwing a kiss","a face heart kiss kissing throwing"],
      ["😗","kissing face","face kissing"],
      ["☺️","white smiling face","face relaxed smiling white"],
      ["😚","kissing face with closed eyes","closed eyes face kissing with"],
      ["😙","kissing face with smiling eyes","eyes face kissing smiling with"],
      ["🥲","smiling face with tear","face smiling tear with"],
      ["😋","face savouring delicious food","delicious face food savouring yum"],
      ["😛","face with stuck-out tongue","face out stuck tongue with"],
      ["😜","face with stuck-out tongue and winking eye","and eye face out stuck tongue winking with"],
      ["🤪","grinning face with one large and one small eye","and eye face grinning large one small with zany"],
      ["😝","face with stuck-out tongue and tightly-closed eyes","and closed eyes face out stuck tightly tongue with"],
      ["🤑","money-mouth face","face money mouth"],
      ["🤗","hugging face","face hugging"],
      ["🤭","smiling face with smiling eyes and hand covering mouth","and covering eyes face hand mouth over smiling with"],
      ["🤫","face with finger covering closed lips","closed covering face finger lips shushing with"],
      ["🤔","thinking face","face thinking"],
      ["🤐","zipper-mouth face","face mouth zipper"],
      ["🤨","face with one eyebrow raised","eyebrow face one raised with"],
      ["😐","neutral face","face neutral"],
      ["😑","expressionless face","expressionless face"],
      ["😶","face without mouth","face mouth no without"],
      ["😏","smirking face","face smirk smirking"],
      ["😒","unamused face","face unamused"],
      ["🙄","face with rolling eyes","eyes face rolling with"],
      ["😬","grimacing face","face grimacing"],
      ["🤥","lying face","face lying"],
      ["😌","relieved face","face relieved"],
      ["😔","pensive face","face pensive"],
      ["😪","sleepy face","face sleepy"],
      ["🤤","drooling face","drooling face"],
      ["😴","sleeping face","face sleeping"],
      ["😷","face with medical mask","face mask medical with"],
      ["🤒","face with thermometer","face thermometer with"],
      ["🤕","face with head-bandage","bandage face head with"],
      ["🤢","nauseated face","face nauseated"],
      ["🤮","face with open mouth vomiting","face mouth open vomiting with"],
      ["🤧","sneezing face","face sneezing"],
      ["🥵","overheated face","face hot overheated"],
      ["🥶","freezing face","cold face freezing"],
      ["🥴","face with uneven eyes and wavy mouth","and eyes face mouth uneven wavy with woozy"],
      ["😵","dizzy face","dizzy face"],
      ["🤯","shocked face with exploding head","exploding face head shocked with"],
      ["🤠","face with cowboy hat","cowboy face hat with"],
      ["🥳","face with party horn and party hat","and face hat horn party partying with"],
      ["🥸","disguised face","disguised face"],
      ["😎","smiling face with sunglasses","face smiling sunglasses with"],
      ["🤓","nerd face","face nerd"],
      ["🧐","face with monocle","face monocle with"],
      ["😕","confused face","confused face"],
      ["😟","worried face","face worried"],
      ["🙁","slightly frowning face","face frowning slightly"],
      ["☹️","white_frowning_face","face frowning white white_frowning_face"],
      ["😮","face with open mouth","face mouth open with"],
      ["😯","hushed face","face hushed"],
      ["😲","astonished face","astonished face"],
      ["😳","flushed face","face flushed"],
      ["🥺","face with pleading eyes","eyes face pleading with"],
      ["😦","frowning face with open mouth","face frowning mouth open with"],
      ["😧","anguished face","anguished face"],
      ["😨","fearful face","face fearful"],
      ["😰","face with open mouth and cold sweat","and cold face mouth open sweat with"],
      ["😥","disappointed but relieved face","but disappointed face relieved"],
      ["😢","crying face","cry crying face"],
      ["😭","loudly crying face","crying face loudly sob"],
      ["😱","face screaming in fear","face fear in scream screaming"],
      ["😖","confounded face","confounded face"],
      ["😣","persevering face","face persevere persevering"],
      ["😞","disappointed face","disappointed face"],
      ["😓","face with cold sweat","cold face sweat with"],
      ["😩","weary face","face weary"],
      ["😫","tired face","face tired"],
      ["🥱","yawning face","face yawning"],
      ["😤","face with look of triumph","face look of triumph with"],
      ["😡","pouting face","face pouting rage"],
      ["😠","angry face","angry face"],
      ["🤬","serious face with symbols covering mouth","covering face mouth on serious symbols with"],
      ["😈","smiling face with horns","face horns imp smiling with"],
      ["👿","imp","imp"],
      ["💀","skull","skull"],
      ["☠️","skull_and_crossbones","and crossbones skull skull_and_crossbones"],
      ["💩","pile of poo","hankey of pile poo poop shit"],
      ["🤡","clown face","clown face"],
      ["👹","japanese ogre","japanese ogre"],
      ["👺","japanese goblin","goblin japanese"],
      ["👻","ghost","ghost"],
      ["👽","extraterrestrial alien","alien extraterrestrial"],
      ["👾","alien monster","alien invader monster space"],
      ["🤖","robot face","face robot"],
      ["😺","smiling cat face with open mouth","cat face mouth open smiley smiling with"],
      ["😸","grinning cat face with smiling eyes","cat eyes face grinning smile smiling with"],
      ["😹","cat face with tears of joy","cat face joy of tears with"],
      ["😻","smiling cat face with heart-shaped eyes","cat eyes face heart shaped smiling with"],
      ["😼","cat face with wry smile","cat face smile smirk with wry"],
      ["😽","kissing cat face with closed eyes","cat closed eyes face kissing with"],
      ["🙀","weary cat face","cat face scream weary"],
      ["😿","crying cat face","cat crying face"],
      ["😾","pouting cat face","cat face pouting"],
      ["🙈","see-no-evil monkey","evil monkey no see"],
      ["🙉","hear-no-evil monkey","evil hear monkey no"],
      ["🙊","speak-no-evil monkey","evil monkey no speak"],
      ["💋","kiss mark","kiss mark"],
      ["💌","love letter","letter love"],
      ["💘","heart with arrow","arrow cupid heart with"],
      ["💝","heart with ribbon","gift heart ribbon with"],
      ["💖","sparkling heart","heart sparkling"],
      ["💗","growing heart","growing heart heartpulse"],
      ["💓","beating heart","beating heart heartbeat"],
      ["💞","revolving hearts","hearts revolving"],
      ["💕","two hearts","hearts two"],
      ["💟","heart decoration","decoration heart"],
      ["❣️","heavy_heart_exclamation_mark_ornament","exclamation heart heavy heavy_heart_exclamation_mark_ornament mark ornament"],
      ["💔","broken heart","broken heart"],
      ["❤️","heavy black heart","black heart heavy"],
      ["🧡","orange heart","heart orange"],
      ["💛","yellow heart","heart yellow"],
      ["💚","green heart","green heart"],
      ["💙","blue heart","blue heart"],
      ["💜","purple heart","heart purple"],
      ["🤎","brown heart","brown heart"],
      ["🖤","black heart","black heart"],
      ["🤍","white heart","heart white"],
      ["💯","hundred points symbol","100 hundred points symbol"],
      ["💢","anger symbol","anger symbol"],
      ["💥","collision symbol","boom collision symbol"],
      ["💫","dizzy symbol","dizzy symbol"],
      ["💦","splashing sweat symbol","drops splashing sweat symbol"],
      ["💨","dash symbol","dash symbol"],
      ["🕳️","hole","hole"],
      ["💣","bomb","bomb"],
      ["💬","speech balloon","balloon speech"],
      ["👁️‍🗨️","eye-in-speech-bubble","bubble eye in speech"],
      ["🗨️","left_speech_bubble","bubble left left_speech_bubble speech"],
      ["🗯️","right_anger_bubble","anger bubble right right_anger_bubble"],
      ["💭","thought balloon","balloon thought"],
      ["💤","sleeping symbol","sleeping symbol zzz"],
    ]
  },
  {
    "name": "People & Body",
    "label": "People",
    "tab": "\ud83d\udc4b",
    "emojis": [
      ["👋","waving hand sign","hand sign wave waving"],
      ["🤚","raised back of hand","back hand of raised"],
      ["🖐️","raised_hand_with_fingers_splayed","fingers hand raised raised_hand_with_fingers_splayed splayed with"],
      ["✋","raised hand","hand raised"],
      ["🖖","raised hand with part between middle and ring fingers","and between fingers hand middle part raised ring spock with"],
      ["👌","ok hand sign","hand ok sign"],
      ["🤌","pinched fingers","fingers pinched"],
      ["🤏","pinching hand","hand pinching"],
      ["✌️","victory hand","hand v victory"],
      ["🤞","hand with index and middle fingers crossed","and crossed fingers hand index middle with"],
      ["🤟","i love you hand sign","hand i love sign you"],
      ["🤘","sign of the horns","horns of sign the"],
      ["🤙","call me hand","call hand me"],
      ["👈","white left pointing backhand index","backhand index left point pointing white"],
      ["👉","white right pointing backhand index","backhand index point pointing right white"],
      ["👆","white up pointing backhand index","2 backhand index point pointing up white"],
      ["🖕","reversed hand with middle finger extended","extended finger hand middle reversed with"],
      ["👇","white down pointing backhand index","backhand down index point pointing white"],
      ["☝️","white up pointing index","index point pointing up white"],
      ["👍","thumbs up sign","+1 sign thumbs thumbsup up"],
      ["👎","thumbs down sign","1 down sign thumbs thumbsdown"],
      ["✊","raised fist","fist raised"],
      ["👊","fisted hand sign","facepunch fisted hand punch sign"],
      ["🤛","left-facing fist","facing fist left"],
      ["🤜","right-facing fist","facing fist right"],
      ["👏","clapping hands sign","clap clapping hands sign"],
      ["🙌","person raising both hands in celebration","both celebration hands in person raised raising"],
      ["👐","open hands sign","hands open sign"],
      ["🤲","palms up together","palms together up"],
      ["🤝","handshake","handshake"],
      ["🙏","person with folded hands","folded hands person pray with"],
      ["✍️","writing_hand","hand writing writing_hand"],
      ["💅","nail polish","care nail polish"],
      ["🤳","selfie","selfie"],
      ["💪","flexed biceps","biceps flexed muscle"],
      ["🦾","mechanical arm","arm mechanical"],
      ["🦿","mechanical leg","leg mechanical"],
      ["🦵","leg","leg"],
      ["🦶","foot","foot"],
      ["👂","ear","ear"],
      ["🦻","ear with hearing aid","aid ear hearing with"],
      ["👃","nose","nose"],
      ["🧠","brain","brain"],
      ["🫀","anatomical heart","anatomical heart"],
      ["🫁","lungs","lungs"],
      ["🦷","tooth","tooth"],
      ["🦴","bone","bone"],
      ["👀","eyes","eyes"],
      ["👁️","eye","eye"],
      ["👅","tongue","tongue"],
      ["👄","mouth","lips mouth"],
      ["👶","baby","baby"],
      ["🧒","child","child"],
      ["👦","boy","boy"],
      ["👧","girl","girl"],
      ["🧑","adult","adult"],
      ["👱","person with blond hair","blond hair person with"],
      ["👨","man","man"],
      ["🧔","bearded person","bearded person"],
      ["👨‍🦰","red_haired_man","haired man red red_haired_man"],
      ["👨‍🦱","curly_haired_man","curly curly_haired_man haired man"],
      ["👨‍🦳","white_haired_man","haired man white white_haired_man"],
      ["👨‍🦲","bald_man","bald bald_man man"],
      ["👩","woman","woman"],
      ["👩‍🦰","red_haired_woman","haired red red_haired_woman woman"],
      ["🧑‍🦰","red_haired_person","haired person red red_haired_person"],
      ["👩‍🦱","curly_haired_woman","curly curly_haired_woman haired woman"],
      ["🧑‍🦱","curly_haired_person","curly curly_haired_person haired person"],
      ["👩‍🦳","white_haired_woman","haired white white_haired_woman woman"],
      ["🧑‍🦳","white_haired_person","haired person white white_haired_person"],
      ["👩‍🦲","bald_woman","bald bald_woman woman"],
      ["🧑‍🦲","bald_person","bald bald_person person"],
      ["👱‍♀️","blond-haired-woman","blond haired woman"],
      ["👱‍♂️","blond-haired-man","blond haired man"],
      ["🧓","older adult","adult older"],
      ["👴","older man","man older"],
      ["👵","older woman","older woman"],
      ["🙍","person frowning","frowning person"],
      ["🙍‍♂️","man-frowning","frowning man"],
      ["🙍‍♀️","woman-frowning","frowning woman"],
      ["🙎","person with pouting face","face person pouting with"],
      ["🙎‍♂️","man-pouting","man pouting"],
      ["🙎‍♀️","woman-pouting","pouting woman"],
      ["🙅","face with no good gesture","face gesture good no with"],
      ["🙅‍♂️","man-gesturing-no","gesturing man no"],
      ["🙅‍♀️","woman-gesturing-no","gesturing no woman"],
      ["🙆","face with ok gesture","face gesture ok with woman"],
      ["🙆‍♂️","man-gesturing-ok","gesturing man ok"],
      ["🙆‍♀️","woman-gesturing-ok","gesturing ok woman"],
      ["💁","information desk person","desk information person"],
      ["💁‍♂️","man-tipping-hand","hand man tipping"],
      ["💁‍♀️","woman-tipping-hand","hand tipping woman"],
      ["🙋","happy person raising one hand","hand happy one person raising"],
      ["🙋‍♂️","man-raising-hand","hand man raising"],
      ["🙋‍♀️","woman-raising-hand","hand raising woman"],
      ["🧏","deaf person","deaf person"],
      ["🧏‍♂️","deaf_man","deaf deaf_man man"],
      ["🧏‍♀️","deaf_woman","deaf deaf_woman woman"],
      ["🙇","person bowing deeply","bow bowing deeply person"],
      ["🙇‍♂️","man-bowing","bowing man"],
      ["🙇‍♀️","woman-bowing","bowing woman"],
      ["🤦","face palm","face palm"],
      ["🤦‍♂️","man-facepalming","facepalming man"],
      ["🤦‍♀️","woman-facepalming","facepalming woman"],
      ["🤷","shrug","shrug"],
      ["🤷‍♂️","man-shrugging","man shrugging"],
      ["🤷‍♀️","woman-shrugging","shrugging woman"],
      ["🧑‍⚕️","health_worker","health health_worker worker"],
      ["👨‍⚕️","male-doctor","doctor male"],
      ["👩‍⚕️","female-doctor","doctor female"],
      ["🧑‍🎓","student","student"],
      ["👨‍🎓","male-student","male student"],
      ["👩‍🎓","female-student","female student"],
      ["🧑‍🏫","teacher","teacher"],
      ["👨‍🏫","male-teacher","male teacher"],
      ["👩‍🏫","female-teacher","female teacher"],
      ["🧑‍⚖️","judge","judge"],
      ["👨‍⚖️","male-judge","judge male"],
      ["👩‍⚖️","female-judge","female judge"],
      ["🧑‍🌾","farmer","farmer"],
      ["👨‍🌾","male-farmer","farmer male"],
      ["👩‍🌾","female-farmer","farmer female"],
      ["🧑‍🍳","cook","cook"],
      ["👨‍🍳","male-cook","cook male"],
      ["👩‍🍳","female-cook","cook female"],
      ["🧑‍🔧","mechanic","mechanic"],
      ["👨‍🔧","male-mechanic","male mechanic"],
      ["👩‍🔧","female-mechanic","female mechanic"],
      ["🧑‍🏭","factory_worker","factory factory_worker worker"],
      ["👨‍🏭","male-factory-worker","factory male worker"],
      ["👩‍🏭","female-factory-worker","factory female worker"],
      ["🧑‍💼","office_worker","office office_worker worker"],
      ["👨‍💼","male-office-worker","male office worker"],
      ["👩‍💼","female-office-worker","female office worker"],
      ["🧑‍🔬","scientist","scientist"],
      ["👨‍🔬","male-scientist","male scientist"],
      ["👩‍🔬","female-scientist","female scientist"],
      ["🧑‍💻","technologist","technologist"],
      ["👨‍💻","male-technologist","male technologist"],
      ["👩‍💻","female-technologist","female technologist"],
      ["🧑‍🎤","singer","singer"],
      ["👨‍🎤","male-singer","male singer"],
      ["👩‍🎤","female-singer","female singer"],
      ["🧑‍🎨","artist","artist"],
      ["👨‍🎨","male-artist","artist male"],
      ["👩‍🎨","female-artist","artist female"],
      ["🧑‍✈️","pilot","pilot"],
      ["👨‍✈️","male-pilot","male pilot"],
      ["👩‍✈️","female-pilot","female pilot"],
      ["🧑‍🚀","astronaut","astronaut"],
      ["👨‍🚀","male-astronaut","astronaut male"],
      ["👩‍🚀","female-astronaut","astronaut female"],
      ["🧑‍🚒","firefighter","firefighter"],
      ["👨‍🚒","male-firefighter","firefighter male"],
      ["👩‍🚒","female-firefighter","female firefighter"],
      ["👮","police officer","cop officer police"],
      ["👮‍♂️","male-police-officer","male officer police"],
      ["👮‍♀️","female-police-officer","female officer police"],
      ["🕵️","sleuth_or_spy","or sleuth sleuth_or_spy spy"],
      ["🕵️‍♂️","male-detective","detective male"],
      ["🕵️‍♀️","female-detective","detective female"],
      ["💂","guardsman","guardsman"],
      ["💂‍♂️","male-guard","guard male"],
      ["💂‍♀️","female-guard","female guard"],
      ["🥷","ninja","ninja"],
      ["👷","construction worker","construction worker"],
      ["👷‍♂️","male-construction-worker","construction male worker"],
      ["👷‍♀️","female-construction-worker","construction female worker"],
      ["🤴","prince","prince"],
      ["👸","princess","princess"],
      ["👳","man with turban","man turban with"],
      ["👳‍♂️","man-wearing-turban","man turban wearing"],
      ["👳‍♀️","woman-wearing-turban","turban wearing woman"],
      ["👲","man with gua pi mao","gua man mao pi with"],
      ["🧕","person with headscarf","headscarf person with"],
      ["🤵‍♂️","man_in_tuxedo","in man man_in_tuxedo tuxedo"],
      ["🤵‍♀️","woman_in_tuxedo","in tuxedo woman woman_in_tuxedo"],
      ["👰","bride with veil","bride veil with"],
      ["👰‍♂️","man_with_veil","man man_with_veil veil with"],
      ["👰‍♀️","woman_with_veil","veil with woman woman_with_veil"],
      ["🤰","pregnant woman","pregnant woman"],
      ["🤱","breast-feeding","breast feeding"],
      ["👩‍🍼","woman_feeding_baby","baby feeding woman woman_feeding_baby"],
      ["👨‍🍼","man_feeding_baby","baby feeding man man_feeding_baby"],
      ["🧑‍🍼","person_feeding_baby","baby feeding person person_feeding_baby"],
      ["👼","baby angel","angel baby"],
      ["🎅","father christmas","christmas father santa"],
      ["🤶","mother christmas","christmas claus mother mrs"],
      ["🧑‍🎄","mx_claus","claus mx mx_claus"],
      ["🦸","superhero","superhero"],
      ["🦸‍♂️","male_superhero","male male_superhero superhero"],
      ["🦸‍♀️","female_superhero","female female_superhero superhero"],
      ["🦹","supervillain","supervillain"],
      ["🦹‍♂️","male_supervillain","male male_supervillain supervillain"],
      ["🦹‍♀️","female_supervillain","female female_supervillain supervillain"],
      ["🧙","mage","mage"],
      ["🧙‍♂️","male_mage","mage male male_mage"],
      ["🧙‍♀️","female_mage","female female_mage mage"],
      ["🧚","fairy","fairy"],
      ["🧚‍♂️","male_fairy","fairy male male_fairy"],
      ["🧚‍♀️","female_fairy","fairy female female_fairy"],
      ["🧛","vampire","vampire"],
      ["🧛‍♂️","male_vampire","male male_vampire vampire"],
      ["🧛‍♀️","female_vampire","female female_vampire vampire"],
      ["🧜","merperson","merperson"],
      ["🧜‍♂️","merman","merman"],
      ["🧜‍♀️","mermaid","mermaid"],
      ["🧝","elf","elf"],
      ["🧝‍♂️","male_elf","elf male male_elf"],
      ["🧝‍♀️","female_elf","elf female female_elf"],
      ["🧞","genie","genie"],
      ["🧞‍♂️","male_genie","genie male male_genie"],
      ["🧞‍♀️","female_genie","female female_genie genie"],
      ["🧟","zombie","zombie"],
      ["🧟‍♂️","male_zombie","male male_zombie zombie"],
      ["🧟‍♀️","female_zombie","female female_zombie zombie"],
      ["💆","face massage","face massage"],
      ["💆‍♂️","man-getting-massage","getting man massage"],
      ["💆‍♀️","woman-getting-massage","getting massage woman"],
      ["💇","haircut","haircut"],
      ["💇‍♂️","man-getting-haircut","getting haircut man"],
      ["💇‍♀️","woman-getting-haircut","getting haircut woman"],
      ["🚶","pedestrian","pedestrian walking"],
      ["🚶‍♂️","man-walking","man walking"],
      ["🚶‍♀️","woman-walking","walking woman"],
      ["🧍","standing person","person standing"],
      ["🧍‍♂️","man_standing","man man_standing standing"],
      ["🧍‍♀️","woman_standing","standing woman woman_standing"],
      ["🧎","kneeling person","kneeling person"],
      ["🧎‍♂️","man_kneeling","kneeling man man_kneeling"],
      ["🧎‍♀️","woman_kneeling","kneeling woman woman_kneeling"],
      ["🧑‍🦯","person_with_probing_cane","cane person person_with_probing_cane probing with"],
      ["👨‍🦯","man_with_probing_cane","cane man man_with_probing_cane probing with"],
      ["👩‍🦯","woman_with_probing_cane","cane probing with woman woman_with_probing_cane"],
      ["🧑‍🦼","person_in_motorized_wheelchair","in motorized person person_in_motorized_wheelchair wheelchair"],
      ["👨‍🦼","man_in_motorized_wheelchair","in man man_in_motorized_wheelchair motorized wheelchair"],
      ["👩‍🦼","woman_in_motorized_wheelchair","in motorized wheelchair woman woman_in_motorized_wheelchair"],
      ["🧑‍🦽","person_in_manual_wheelchair","in manual person person_in_manual_wheelchair wheelchair"],
      ["👨‍🦽","man_in_manual_wheelchair","in man man_in_manual_wheelchair manual wheelchair"],
      ["👩‍🦽","woman_in_manual_wheelchair","in manual wheelchair woman woman_in_manual_wheelchair"],
      ["🏃","runner","runner running"],
      ["🏃‍♂️","man-running","man running"],
      ["🏃‍♀️","woman-running","running woman"],
      ["💃","dancer","dancer"],
      ["🕺","man dancing","dancing man"],
      ["🕴️","man_in_business_suit_levitating","business in levitating man man_in_business_suit_levitating suit"],
      ["👯","woman with bunny ears","bunny dancers ears with woman"],
      ["👯‍♂️","man-with-bunny-ears-partying","bunny ears man partying with"],
      ["👯‍♀️","woman-with-bunny-ears-partying","bunny ears partying with woman"],
      ["🧖","person in steamy room","in person room steamy"],
      ["🧖‍♂️","man_in_steamy_room","in man man_in_steamy_room room steamy"],
      ["🧖‍♀️","woman_in_steamy_room","in room steamy woman woman_in_steamy_room"],
      ["🧗","person climbing","climbing person"],
      ["🧗‍♂️","man_climbing","climbing man man_climbing"],
      ["🧗‍♀️","woman_climbing","climbing woman woman_climbing"],
      ["🤺","fencer","fencer"],
      ["🏇","horse racing","horse racing"],
      ["⛷️","skier","skier"],
      ["🏂","snowboarder","snowboarder"],
      ["🏌️","golfer","golfer"],
      ["🏌️‍♂️","man-golfing","golfing man"],
      ["🏌️‍♀️","woman-golfing","golfing woman"],
      ["🏄","surfer","surfer"],
      ["🏄‍♂️","man-surfing","man surfing"],
      ["🏄‍♀️","woman-surfing","surfing woman"],
      ["🚣","rowboat","rowboat"],
      ["🚣‍♂️","man-rowing-boat","boat man rowing"],
      ["🚣‍♀️","woman-rowing-boat","boat rowing woman"],
      ["🏊","swimmer","swimmer"],
      ["🏊‍♂️","man-swimming","man swimming"],
      ["🏊‍♀️","woman-swimming","swimming woman"],
      ["⛹️","person_with_ball","ball person person_with_ball with"],
      ["⛹️‍♂️","man-bouncing-ball","ball bouncing man"],
      ["⛹️‍♀️","woman-bouncing-ball","ball bouncing woman"],
      ["🏋️","weight_lifter","lifter weight weight_lifter"],
      ["🏋️‍♂️","man-lifting-weights","lifting man weights"],
      ["🏋️‍♀️","woman-lifting-weights","lifting weights woman"],
      ["🚴","bicyclist","bicyclist"],
      ["🚴‍♂️","man-biking","biking man"],
      ["🚴‍♀️","woman-biking","biking woman"],
      ["🚵","mountain bicyclist","bicyclist mountain"],
      ["🚵‍♂️","man-mountain-biking","biking man mountain"],
      ["🚵‍♀️","woman-mountain-biking","biking mountain woman"],
      ["🤸","person doing cartwheel","cartwheel doing person"],
      ["🤸‍♂️","man-cartwheeling","cartwheeling man"],
      ["🤸‍♀️","woman-cartwheeling","cartwheeling woman"],
      ["🤼","wrestlers","wrestlers"],
      ["🤼‍♂️","man-wrestling","man wrestling"],
      ["🤼‍♀️","woman-wrestling","woman wrestling"],
      ["🤽","water polo","polo water"],
      ["🤽‍♂️","man-playing-water-polo","man playing polo water"],
      ["🤽‍♀️","woman-playing-water-polo","playing polo water woman"],
      ["🤾","handball","handball"],
      ["🤾‍♂️","man-playing-handball","handball man playing"],
      ["🤾‍♀️","woman-playing-handball","handball playing woman"],
      ["🤹","juggling","juggling"],
      ["🤹‍♂️","man-juggling","juggling man"],
      ["🤹‍♀️","woman-juggling","juggling woman"],
      ["🧘","person in lotus position","in lotus person position"],
      ["🧘‍♂️","man_in_lotus_position","in lotus man man_in_lotus_position position"],
      ["🧘‍♀️","woman_in_lotus_position","in lotus position woman woman_in_lotus_position"],
      ["🛀","bath","bath"],
      ["🛌","sleeping accommodation","accommodation sleeping"],
      ["🧑‍🤝‍🧑","people_holding_hands","hands holding people people_holding_hands"],
      ["👭","two women holding hands","hands holding two women"],
      ["👫","man and woman holding hands","and couple hands holding man woman"],
      ["👬","two men holding hands","hands holding men two"],
      ["💏","kiss","couplekiss kiss"],
      ["👩‍❤️‍💋‍👨","woman-kiss-man","kiss man woman"],
      ["👨‍❤️‍💋‍👨","man-kiss-man","kiss man"],
      ["👩‍❤️‍💋‍👩","woman-kiss-woman","kiss woman"],
      ["💑","couple with heart","couple heart with"],
      ["👩‍❤️‍👨","woman-heart-man","heart man woman"],
      ["👨‍❤️‍👨","man-heart-man","heart man"],
      ["👩‍❤️‍👩","woman-heart-woman","heart woman"],
      ["👪","family","boy family man woman"],
      ["👨‍👩‍👦","man-woman-boy","boy family man woman"],
      ["👨‍👩‍👧","man-woman-girl","girl man woman"],
      ["👨‍👩‍👧‍👦","man-woman-girl-boy","boy girl man woman"],
      ["👨‍👩‍👦‍👦","man-woman-boy-boy","boy man woman"],
      ["👨‍👩‍👧‍👧","man-woman-girl-girl","girl man woman"],
      ["👨‍👨‍👦","man-man-boy","boy man"],
      ["👨‍👨‍👧","man-man-girl","girl man"],
      ["👨‍👨‍👧‍👦","man-man-girl-boy","boy girl man"],
      ["👨‍👨‍👦‍👦","man-man-boy-boy","boy man"],
      ["👨‍👨‍👧‍👧","man-man-girl-girl","girl man"],
      ["👩‍👩‍👦","woman-woman-boy","boy woman"],
      ["👩‍👩‍👧","woman-woman-girl","girl woman"],
      ["👩‍👩‍👧‍👦","woman-woman-girl-boy","boy girl woman"],
      ["👩‍👩‍👦‍👦","woman-woman-boy-boy","boy woman"],
      ["👩‍👩‍👧‍👧","woman-woman-girl-girl","girl woman"],
      ["👨‍👦","man-boy","boy man"],
      ["👨‍👦‍👦","man-boy-boy","boy man"],
      ["👨‍👧","man-girl","girl man"],
      ["👨‍👧‍👦","man-girl-boy","boy girl man"],
      ["👨‍👧‍👧","man-girl-girl","girl man"],
      ["👩‍👦","woman-boy","boy woman"],
      ["👩‍👦‍👦","woman-boy-boy","boy woman"],
      ["👩‍👧","woman-girl","girl woman"],
      ["👩‍👧‍👦","woman-girl-boy","boy girl woman"],
      ["👩‍👧‍👧","woman-girl-girl","girl woman"],
      ["🗣️","speaking_head_in_silhouette","head in silhouette speaking speaking_head_in_silhouette"],
      ["👤","bust in silhouette","bust in silhouette"],
      ["👥","busts in silhouette","busts in silhouette"],
      ["🫂","people hugging","hugging people"],
      ["👣","footprints","footprints"],
      ["🤵","man in tuxedo","in man tuxedo"],
    ]
  },
  {
    "name": "Animals & Nature",
    "label": "Nature",
    "tab": "\ud83d\udc3b",
    "emojis": [
      ["🐵","monkey face","face monkey"],
      ["🐒","monkey","monkey"],
      ["🦍","gorilla","gorilla"],
      ["🦧","orangutan","orangutan"],
      ["🐶","dog face","dog face"],
      ["🐕","dog","dog dog2"],
      ["🦮","guide dog","dog guide"],
      ["🐕‍🦺","service_dog","dog service service_dog"],
      ["🐩","poodle","poodle"],
      ["🐺","wolf face","face wolf"],
      ["🦊","fox face","face fox"],
      ["🦝","raccoon","raccoon"],
      ["🐱","cat face","cat face"],
      ["🐈","cat","cat cat2"],
      ["🐈‍⬛","black_cat","black black_cat cat"],
      ["🦁","lion face","face lion"],
      ["🐯","tiger face","face tiger"],
      ["🐅","tiger","tiger tiger2"],
      ["🐆","leopard","leopard"],
      ["🐴","horse face","face horse"],
      ["🐎","horse","horse racehorse"],
      ["🦄","unicorn face","face unicorn"],
      ["🦓","zebra face","face zebra"],
      ["🦌","deer","deer"],
      ["🦬","bison","bison"],
      ["🐮","cow face","cow face"],
      ["🐂","ox","ox"],
      ["🐃","water buffalo","buffalo water"],
      ["🐄","cow","cow cow2"],
      ["🐷","pig face","face pig"],
      ["🐖","pig","pig pig2"],
      ["🐗","boar","boar"],
      ["🐽","pig nose","nose pig"],
      ["🐏","ram","ram"],
      ["🐑","sheep","sheep"],
      ["🐐","goat","goat"],
      ["🐪","dromedary camel","camel dromedary"],
      ["🐫","bactrian camel","bactrian camel"],
      ["🦙","llama","llama"],
      ["🦒","giraffe face","face giraffe"],
      ["🐘","elephant","elephant"],
      ["🦣","mammoth","mammoth"],
      ["🦏","rhinoceros","rhinoceros"],
      ["🦛","hippopotamus","hippopotamus"],
      ["🐭","mouse face","face mouse"],
      ["🐁","mouse","mouse mouse2"],
      ["🐀","rat","rat"],
      ["🐹","hamster face","face hamster"],
      ["🐰","rabbit face","face rabbit"],
      ["🐇","rabbit","rabbit rabbit2"],
      ["🐿️","chipmunk","chipmunk"],
      ["🦫","beaver","beaver"],
      ["🦔","hedgehog","hedgehog"],
      ["🦇","bat","bat"],
      ["🐻","bear face","bear face"],
      ["🐻‍❄️","polar_bear","bear polar polar_bear"],
      ["🐨","koala","koala"],
      ["🐼","panda face","face panda"],
      ["🦥","sloth","sloth"],
      ["🦦","otter","otter"],
      ["🦨","skunk","skunk"],
      ["🦘","kangaroo","kangaroo"],
      ["🦡","badger","badger"],
      ["🐾","paw prints","feet paw prints"],
      ["🦃","turkey","turkey"],
      ["🐔","chicken","chicken"],
      ["🐓","rooster","rooster"],
      ["🐣","hatching chick","chick hatching"],
      ["🐤","baby chick","baby chick"],
      ["🐥","front-facing baby chick","baby chick facing front hatched"],
      ["🐦","bird","bird"],
      ["🐧","penguin","penguin"],
      ["🕊️","dove_of_peace","dove dove_of_peace of peace"],
      ["🦅","eagle","eagle"],
      ["🦆","duck","duck"],
      ["🦢","swan","swan"],
      ["🦉","owl","owl"],
      ["🦤","dodo","dodo"],
      ["🪶","feather","feather"],
      ["🦩","flamingo","flamingo"],
      ["🦚","peacock","peacock"],
      ["🦜","parrot","parrot"],
      ["🐸","frog face","face frog"],
      ["🐊","crocodile","crocodile"],
      ["🐢","turtle","turtle"],
      ["🦎","lizard","lizard"],
      ["🐍","snake","snake"],
      ["🐲","dragon face","dragon face"],
      ["🐉","dragon","dragon"],
      ["🦕","sauropod","sauropod"],
      ["🦖","t-rex","rex t"],
      ["🐳","spouting whale","spouting whale"],
      ["🐋","whale","whale whale2"],
      ["🐬","dolphin","dolphin flipper"],
      ["🦭","seal","seal"],
      ["🐟","fish","fish"],
      ["🐠","tropical fish","fish tropical"],
      ["🐡","blowfish","blowfish"],
      ["🦈","shark","shark"],
      ["🐙","octopus","octopus"],
      ["🐚","spiral shell","shell spiral"],
      ["🐌","snail","snail"],
      ["🦋","butterfly","butterfly"],
      ["🐛","bug","bug"],
      ["🐜","ant","ant"],
      ["🐝","honeybee","bee honeybee"],
      ["🪲","beetle","beetle"],
      ["🦗","cricket","cricket"],
      ["🪳","cockroach","cockroach"],
      ["🕷️","spider","spider"],
      ["🕸️","spider_web","spider spider_web web"],
      ["🦂","scorpion","scorpion"],
      ["🦟","mosquito","mosquito"],
      ["🪰","fly","fly"],
      ["🪱","worm","worm"],
      ["🦠","microbe","microbe"],
      ["💐","bouquet","bouquet"],
      ["🌸","cherry blossom","blossom cherry"],
      ["💮","white flower","flower white"],
      ["🏵️","rosette","rosette"],
      ["🌹","rose","rose"],
      ["🥀","wilted flower","flower wilted"],
      ["🌺","hibiscus","hibiscus"],
      ["🌻","sunflower","sunflower"],
      ["🌼","blossom","blossom"],
      ["🌷","tulip","tulip"],
      ["🌱","seedling","seedling"],
      ["🪴","potted plant","plant potted"],
      ["🌲","evergreen tree","evergreen tree"],
      ["🌳","deciduous tree","deciduous tree"],
      ["🌴","palm tree","palm tree"],
      ["🌵","cactus","cactus"],
      ["🌾","ear of rice","ear of rice"],
      ["🌿","herb","herb"],
      ["☘️","shamrock","shamrock"],
      ["🍀","four leaf clover","clover four leaf"],
      ["🍁","maple leaf","leaf maple"],
      ["🍂","fallen leaf","fallen leaf"],
      ["🍃","leaf fluttering in wind","fluttering in leaf leaves wind"],
      ["🐞","lady beetle","beetle lady"],
    ]
  },
  {
    "name": "Food & Drink",
    "label": "Food",
    "tab": "\ud83c\udf54",
    "emojis": [
      ["🍇","grapes","grapes"],
      ["🍈","melon","melon"],
      ["🍉","watermelon","watermelon"],
      ["🍊","tangerine","tangerine"],
      ["🍋","lemon","lemon"],
      ["🍌","banana","banana"],
      ["🍍","pineapple","pineapple"],
      ["🥭","mango","mango"],
      ["🍎","red apple","apple red"],
      ["🍏","green apple","apple green"],
      ["🍐","pear","pear"],
      ["🍑","peach","peach"],
      ["🍒","cherries","cherries"],
      ["🍓","strawberry","strawberry"],
      ["🫐","blueberries","blueberries"],
      ["🥝","kiwifruit","kiwifruit"],
      ["🍅","tomato","tomato"],
      ["🫒","olive","olive"],
      ["🥥","coconut","coconut"],
      ["🥑","avocado","avocado"],
      ["🍆","aubergine","aubergine eggplant"],
      ["🥔","potato","potato"],
      ["🥕","carrot","carrot"],
      ["🌽","ear of maize","corn ear maize of"],
      ["🌶️","hot_pepper","hot hot_pepper pepper"],
      ["🫑","bell pepper","bell pepper"],
      ["🥒","cucumber","cucumber"],
      ["🥬","leafy green","green leafy"],
      ["🥦","broccoli","broccoli"],
      ["🧄","garlic","garlic"],
      ["🧅","onion","onion"],
      ["🍄","mushroom","mushroom"],
      ["🥜","peanuts","peanuts"],
      ["🌰","chestnut","chestnut"],
      ["🍞","bread","bread"],
      ["🥐","croissant","croissant"],
      ["🥖","baguette bread","baguette bread"],
      ["🫓","flatbread","flatbread"],
      ["🥨","pretzel","pretzel"],
      ["🥯","bagel","bagel"],
      ["🥞","pancakes","pancakes"],
      ["🧇","waffle","waffle"],
      ["🧀","cheese wedge","cheese wedge"],
      ["🍖","meat on bone","bone meat on"],
      ["🍗","poultry leg","leg poultry"],
      ["🥩","cut of meat","cut meat of"],
      ["🥓","bacon","bacon"],
      ["🍔","hamburger","hamburger"],
      ["🍟","french fries","french fries"],
      ["🍕","slice of pizza","of pizza slice"],
      ["🌭","hot dog","dog hot hotdog"],
      ["🥪","sandwich","sandwich"],
      ["🌮","taco","taco"],
      ["🌯","burrito","burrito"],
      ["🫔","tamale","tamale"],
      ["🥙","stuffed flatbread","flatbread stuffed"],
      ["🧆","falafel","falafel"],
      ["🥚","egg","egg"],
      ["🍳","cooking","cooking egg fried"],
      ["🥘","shallow pan of food","food of pan shallow"],
      ["🍲","pot of food","food of pot stew"],
      ["🫕","fondue","fondue"],
      ["🥣","bowl with spoon","bowl spoon with"],
      ["🥗","green salad","green salad"],
      ["🍿","popcorn","popcorn"],
      ["🧈","butter","butter"],
      ["🧂","salt shaker","salt shaker"],
      ["🥫","canned food","canned food"],
      ["🍱","bento box","bento box"],
      ["🍘","rice cracker","cracker rice"],
      ["🍙","rice ball","ball rice"],
      ["🍚","cooked rice","cooked rice"],
      ["🍛","curry and rice","and curry rice"],
      ["🍜","steaming bowl","bowl ramen steaming"],
      ["🍝","spaghetti","spaghetti"],
      ["🍠","roasted sweet potato","potato roasted sweet"],
      ["🍢","oden","oden"],
      ["🍣","sushi","sushi"],
      ["🍤","fried shrimp","fried shrimp"],
      ["🍥","fish cake with swirl design","cake design fish swirl with"],
      ["🥮","moon cake","cake moon"],
      ["🍡","dango","dango"],
      ["🥟","dumpling","dumpling"],
      ["🥠","fortune cookie","cookie fortune"],
      ["🥡","takeout box","box takeout"],
      ["🦀","crab","crab"],
      ["🦞","lobster","lobster"],
      ["🦐","shrimp","shrimp"],
      ["🦑","squid","squid"],
      ["🦪","oyster","oyster"],
      ["🍦","soft ice cream","cream ice icecream soft"],
      ["🍧","shaved ice","ice shaved"],
      ["🍨","ice cream","cream ice"],
      ["🍩","doughnut","doughnut"],
      ["🍪","cookie","cookie"],
      ["🎂","birthday cake","birthday cake"],
      ["🍰","shortcake","cake shortcake"],
      ["🧁","cupcake","cupcake"],
      ["🥧","pie","pie"],
      ["🍫","chocolate bar","bar chocolate"],
      ["🍬","candy","candy"],
      ["🍭","lollipop","lollipop"],
      ["🍮","custard","custard"],
      ["🍯","honey pot","honey pot"],
      ["🍼","baby bottle","baby bottle"],
      ["🥛","glass of milk","glass milk of"],
      ["☕","hot beverage","beverage coffee hot"],
      ["🫖","teapot","teapot"],
      ["🍵","teacup without handle","handle tea teacup without"],
      ["🍶","sake bottle and cup","and bottle cup sake"],
      ["🍾","bottle with popping cork","bottle champagne cork popping with"],
      ["🍷","wine glass","glass wine"],
      ["🍸","cocktail glass","cocktail glass"],
      ["🍹","tropical drink","drink tropical"],
      ["🍺","beer mug","beer mug"],
      ["🍻","clinking beer mugs","beer beers clinking mugs"],
      ["🥂","clinking glasses","clinking glasses"],
      ["🥃","tumbler glass","glass tumbler"],
      ["🥤","cup with straw","cup straw with"],
      ["🧋","bubble tea","bubble tea"],
      ["🧃","beverage box","beverage box"],
      ["🧉","mate drink","drink mate"],
      ["🧊","ice cube","cube ice"],
      ["🥢","chopsticks","chopsticks"],
      ["🍽️","knife_fork_plate","fork knife knife_fork_plate plate"],
      ["🍴","fork and knife","and fork knife"],
      ["🥄","spoon","spoon"],
      ["🔪","hocho","hocho knife"],
      ["🏺","amphora","amphora"],
    ]
  },
  {
    "name": "Travel & Places",
    "label": "Travel",
    "tab": "\u2708\ufe0f",
    "emojis": [
      ["🌍","earth globe europe-africa","africa earth europe globe"],
      ["🌎","earth globe americas","americas earth globe"],
      ["🌏","earth globe asia-australia","asia australia earth globe"],
      ["🌐","globe with meridians","globe meridians with"],
      ["🗺️","world_map","map world world_map"],
      ["🗾","silhouette of japan","japan of silhouette"],
      ["🧭","compass","compass"],
      ["🏔️","snow_capped_mountain","capped mountain snow snow_capped_mountain"],
      ["⛰️","mountain","mountain"],
      ["🌋","volcano","volcano"],
      ["🗻","mount fuji","fuji mount"],
      ["🏕️","camping","camping"],
      ["🏖️","beach_with_umbrella","beach beach_with_umbrella umbrella with"],
      ["🏜️","desert","desert"],
      ["🏝️","desert_island","desert desert_island island"],
      ["🏞️","national_park","national national_park park"],
      ["🏟️","stadium","stadium"],
      ["🏛️","classical_building","building classical classical_building"],
      ["🏗️","building_construction","building building_construction construction"],
      ["🧱","brick","brick bricks"],
      ["🪨","rock","rock"],
      ["🪵","wood","wood"],
      ["🛖","hut","hut"],
      ["🏘️","house_buildings","buildings house house_buildings"],
      ["🏚️","derelict_house_building","building derelict derelict_house_building house"],
      ["🏠","house building","building house"],
      ["🏡","house with garden","garden house with"],
      ["🏢","office building","building office"],
      ["🏣","japanese post office","japanese office post"],
      ["🏤","european post office","european office post"],
      ["🏥","hospital","hospital"],
      ["🏦","bank","bank"],
      ["🏨","hotel","hotel"],
      ["🏩","love hotel","hotel love"],
      ["🏪","convenience store","convenience store"],
      ["🏫","school","school"],
      ["🏬","department store","department store"],
      ["🏭","factory","factory"],
      ["🏯","japanese castle","castle japanese"],
      ["🏰","european castle","castle european"],
      ["💒","wedding","wedding"],
      ["🗼","tokyo tower","tokyo tower"],
      ["🗽","statue of liberty","liberty of statue"],
      ["⛪","church","church"],
      ["🕌","mosque","mosque"],
      ["🛕","hindu temple","hindu temple"],
      ["🕍","synagogue","synagogue"],
      ["⛩️","shinto_shrine","shinto shinto_shrine shrine"],
      ["🕋","kaaba","kaaba"],
      ["⛲","fountain","fountain"],
      ["⛺","tent","tent"],
      ["🌁","foggy","foggy"],
      ["🌃","night with stars","night stars with"],
      ["🏙️","cityscape","cityscape"],
      ["🌄","sunrise over mountains","mountains over sunrise"],
      ["🌅","sunrise","sunrise"],
      ["🌆","cityscape at dusk","at city cityscape dusk sunset"],
      ["🌇","sunset over buildings","buildings city over sunrise sunset"],
      ["🌉","bridge at night","at bridge night"],
      ["♨️","hot springs","hot hotsprings springs"],
      ["🎠","carousel horse","carousel horse"],
      ["🎡","ferris wheel","ferris wheel"],
      ["🎢","roller coaster","coaster roller"],
      ["💈","barber pole","barber pole"],
      ["🎪","circus tent","circus tent"],
      ["🚂","steam locomotive","locomotive steam"],
      ["🚃","railway car","car railway"],
      ["🚄","high-speed train","bullettrain high side speed train"],
      ["🚅","high-speed train with bullet nose","bullet bullettrain front high nose speed train with"],
      ["🚆","train","train train2"],
      ["🚇","metro","metro"],
      ["🚈","light rail","light rail"],
      ["🚉","station","station"],
      ["🚊","tram","tram"],
      ["🚝","monorail","monorail"],
      ["🚞","mountain railway","mountain railway"],
      ["🚋","tram car","car train tram"],
      ["🚌","bus","bus"],
      ["🚍","oncoming bus","bus oncoming"],
      ["🚎","trolleybus","trolleybus"],
      ["🚐","minibus","minibus"],
      ["🚑","ambulance","ambulance"],
      ["🚒","fire engine","engine fire"],
      ["🚓","police car","car police"],
      ["🚔","oncoming police car","car oncoming police"],
      ["🚕","taxi","taxi"],
      ["🚖","oncoming taxi","oncoming taxi"],
      ["🚗","automobile","automobile car red"],
      ["🚘","oncoming automobile","automobile oncoming"],
      ["🚙","recreational vehicle","blue car recreational vehicle"],
      ["🛻","pickup truck","pickup truck"],
      ["🚚","delivery truck","delivery truck"],
      ["🚛","articulated lorry","articulated lorry"],
      ["🚜","tractor","tractor"],
      ["🏎️","racing_car","car racing racing_car"],
      ["🏍️","racing_motorcycle","motorcycle racing racing_motorcycle"],
      ["🛵","motor scooter","motor scooter"],
      ["🦽","manual wheelchair","manual wheelchair"],
      ["🦼","motorized wheelchair","motorized wheelchair"],
      ["🛺","auto rickshaw","auto rickshaw"],
      ["🚲","bicycle","bicycle bike"],
      ["🛴","scooter","scooter"],
      ["🛹","skateboard","skateboard"],
      ["🛼","roller skate","roller skate"],
      ["🚏","bus stop","bus busstop stop"],
      ["🛣️","motorway","motorway"],
      ["🛤️","railway_track","railway railway_track track"],
      ["🛢️","oil_drum","drum oil oil_drum"],
      ["⛽","fuel pump","fuel fuelpump pump"],
      ["🚨","police cars revolving light","cars light police revolving rotating"],
      ["🚥","horizontal traffic light","horizontal light traffic"],
      ["🚦","vertical traffic light","light traffic vertical"],
      ["🛑","octagonal sign","octagonal sign"],
      ["🚧","construction sign","construction sign"],
      ["⚓","anchor","anchor"],
      ["⛵","sailboat","boat sailboat"],
      ["🛶","canoe","canoe"],
      ["🚤","speedboat","speedboat"],
      ["🛳️","passenger_ship","passenger passenger_ship ship"],
      ["⛴️","ferry","ferry"],
      ["🛥️","motor_boat","boat motor motor_boat"],
      ["🚢","ship","ship"],
      ["✈️","airplane","airplane"],
      ["🛩️","small_airplane","airplane small small_airplane"],
      ["🛫","airplane departure","airplane departure"],
      ["🛬","airplane arriving","airplane arriving"],
      ["🪂","parachute","parachute"],
      ["💺","seat","seat"],
      ["🚁","helicopter","helicopter"],
      ["🚟","suspension railway","railway suspension"],
      ["🚠","mountain cableway","cableway mountain"],
      ["🚡","aerial tramway","aerial tramway"],
      ["🛰️","satellite","satellite"],
      ["🚀","rocket","rocket"],
      ["🛸","flying saucer","flying saucer"],
      ["🛎️","bellhop_bell","bell bellhop bellhop_bell"],
      ["🧳","luggage","luggage"],
      ["⌛","hourglass","hourglass"],
      ["⏳","hourglass with flowing sand","flowing hourglass sand with"],
      ["⌚","watch","watch"],
      ["⏰","alarm clock","alarm clock"],
      ["⏱️","stopwatch","stopwatch"],
      ["⏲️","timer_clock","clock timer timer_clock"],
      ["🕰️","mantelpiece_clock","clock mantelpiece mantelpiece_clock"],
      ["🕛","clock face twelve oclock","clock clock12 face oclock twelve"],
      ["🕧","clock face twelve-thirty","clock clock1230 face thirty twelve"],
      ["🕐","clock face one oclock","clock clock1 face oclock one"],
      ["🕜","clock face one-thirty","clock clock130 face one thirty"],
      ["🕑","clock face two oclock","clock clock2 face oclock two"],
      ["🕝","clock face two-thirty","clock clock230 face thirty two"],
      ["🕒","clock face three oclock","clock clock3 face oclock three"],
      ["🕞","clock face three-thirty","clock clock330 face thirty three"],
      ["🕓","clock face four oclock","clock clock4 face four oclock"],
      ["🕟","clock face four-thirty","clock clock430 face four thirty"],
      ["🕔","clock face five oclock","clock clock5 face five oclock"],
      ["🕠","clock face five-thirty","clock clock530 face five thirty"],
      ["🕕","clock face six oclock","clock clock6 face oclock six"],
      ["🕡","clock face six-thirty","clock clock630 face six thirty"],
      ["🕖","clock face seven oclock","clock clock7 face oclock seven"],
      ["🕢","clock face seven-thirty","clock clock730 face seven thirty"],
      ["🕗","clock face eight oclock","clock clock8 eight face oclock"],
      ["🕣","clock face eight-thirty","clock clock830 eight face thirty"],
      ["🕘","clock face nine oclock","clock clock9 face nine oclock"],
      ["🕤","clock face nine-thirty","clock clock930 face nine thirty"],
      ["🕙","clock face ten oclock","clock clock10 face oclock ten"],
      ["🕥","clock face ten-thirty","clock clock1030 face ten thirty"],
      ["🕚","clock face eleven oclock","clock clock11 eleven face oclock"],
      ["🕦","clock face eleven-thirty","clock clock1130 eleven face thirty"],
      ["🌑","new moon symbol","moon new symbol"],
      ["🌒","waxing crescent moon symbol","crescent moon symbol waxing"],
      ["🌓","first quarter moon symbol","first moon quarter symbol"],
      ["🌔","waxing gibbous moon symbol","gibbous moon symbol waxing"],
      ["🌕","full moon symbol","full moon symbol"],
      ["🌖","waning gibbous moon symbol","gibbous moon symbol waning"],
      ["🌗","last quarter moon symbol","last moon quarter symbol"],
      ["🌘","waning crescent moon symbol","crescent moon symbol waning"],
      ["🌙","crescent moon","crescent moon"],
      ["🌚","new moon with face","face moon new with"],
      ["🌛","first quarter moon with face","face first moon quarter with"],
      ["🌜","last quarter moon with face","face last moon quarter with"],
      ["🌡️","thermometer","thermometer"],
      ["☀️","black sun with rays","black rays sun sunny with"],
      ["🌝","full moon with face","face full moon with"],
      ["🌞","sun with face","face sun with"],
      ["🪐","ringed planet","planet ringed"],
      ["⭐","white medium star","medium star white"],
      ["🌟","glowing star","glowing star star2"],
      ["🌠","shooting star","shooting star stars"],
      ["🌌","milky way","milky way"],
      ["☁️","cloud","cloud"],
      ["⛅","sun behind cloud","behind cloud partly sun sunny"],
      ["⛈️","thunder_cloud_and_rain","and cloud rain thunder thunder_cloud_and_rain"],
      ["🌤️","mostly_sunny","cloud mostly mostly_sunny small sun sunny"],
      ["🌥️","barely_sunny","barely barely_sunny behind cloud sun sunny"],
      ["🌦️","partly_sunny_rain","behind cloud partly partly_sunny_rain rain sun sunny"],
      ["🌧️","rain_cloud","cloud rain rain_cloud"],
      ["🌨️","snow_cloud","cloud snow snow_cloud"],
      ["🌩️","lightning","cloud lightning"],
      ["🌪️","tornado","cloud tornado"],
      ["🌫️","fog","fog"],
      ["🌬️","wind_blowing_face","blowing face wind wind_blowing_face"],
      ["🌀","cyclone","cyclone"],
      ["🌈","rainbow","rainbow"],
      ["🌂","closed umbrella","closed umbrella"],
      ["☂️","umbrella","umbrella"],
      ["☔","umbrella with rain drops","drops rain umbrella with"],
      ["⛱️","umbrella_on_ground","ground on umbrella umbrella_on_ground"],
      ["⚡","high voltage sign","high sign voltage zap"],
      ["❄️","snowflake","snowflake"],
      ["☃️","snowman","snowman"],
      ["⛄","snowman without snow","snow snowman without"],
      ["☄️","comet","comet"],
      ["🔥","fire","fire"],
      ["💧","droplet","droplet"],
      ["🌊","water wave","ocean water wave"],
    ]
  },
  {
    "name": "Activities",
    "label": "Activities",
    "tab": "\u26bd",
    "emojis": [
      ["🎃","jack-o-lantern","jack lantern o"],
      ["🎄","christmas tree","christmas tree"],
      ["🎆","fireworks","fireworks"],
      ["🎇","firework sparkler","firework sparkler"],
      ["🧨","firecracker","firecracker"],
      ["✨","sparkles","sparkles"],
      ["🎈","balloon","balloon"],
      ["🎉","party popper","party popper tada"],
      ["🎊","confetti ball","ball confetti"],
      ["🎋","tanabata tree","tanabata tree"],
      ["🎍","pine decoration","bamboo decoration pine"],
      ["🎎","japanese dolls","dolls japanese"],
      ["🎏","carp streamer","carp flags streamer"],
      ["🎐","wind chime","chime wind"],
      ["🎑","moon viewing ceremony","ceremony moon rice scene viewing"],
      ["🧧","red gift envelope","envelope gift red"],
      ["🎀","ribbon","ribbon"],
      ["🎁","wrapped present","gift present wrapped"],
      ["🎗️","reminder_ribbon","reminder reminder_ribbon ribbon"],
      ["🎟️","admission_tickets","admission admission_tickets tickets"],
      ["🎫","ticket","ticket"],
      ["🎖️","medal","medal"],
      ["🏆","trophy","trophy"],
      ["🏅","sports medal","medal sports"],
      ["🥇","first place medal","first medal place"],
      ["🥈","second place medal","medal place second"],
      ["🥉","third place medal","medal place third"],
      ["⚽","soccer ball","ball soccer"],
      ["⚾","baseball","baseball"],
      ["🥎","softball","softball"],
      ["🏀","basketball and hoop","and basketball hoop"],
      ["🏐","volleyball","volleyball"],
      ["🏈","american football","american football"],
      ["🏉","rugby football","football rugby"],
      ["🎾","tennis racquet and ball","and ball racquet tennis"],
      ["🥏","flying disc","disc flying"],
      ["🎳","bowling","bowling"],
      ["🏏","cricket bat and ball","and ball bat cricket"],
      ["🏑","field hockey stick and ball","and ball field hockey stick"],
      ["🏒","ice hockey stick and puck","and hockey ice puck stick"],
      ["🥍","lacrosse stick and ball","and ball lacrosse stick"],
      ["🏓","table tennis paddle and ball","and ball paddle table tennis"],
      ["🏸","badminton racquet and shuttlecock","and badminton racquet shuttlecock"],
      ["🥊","boxing glove","boxing glove"],
      ["🥋","martial arts uniform","arts martial uniform"],
      ["🥅","goal net","goal net"],
      ["⛳","flag in hole","flag golf hole in"],
      ["⛸️","ice_skate","ice ice_skate skate"],
      ["🎣","fishing pole and fish","and fish fishing pole"],
      ["🤿","diving mask","diving mask"],
      ["🎽","running shirt with sash","running sash shirt with"],
      ["🎿","ski and ski boot","and boot ski"],
      ["🛷","sled","sled"],
      ["🥌","curling stone","curling stone"],
      ["🎯","direct hit","dart direct hit"],
      ["🪀","yo-yo","yo"],
      ["🪁","kite","kite"],
      ["🎱","billiards","8ball billiards"],
      ["🔮","crystal ball","ball crystal"],
      ["🪄","magic wand","magic wand"],
      ["🧿","nazar amulet","amulet nazar"],
      ["🎮","video game","game video"],
      ["🕹️","joystick","joystick"],
      ["🎰","slot machine","machine slot"],
      ["🎲","game die","die game"],
      ["🧩","jigsaw puzzle piece","jigsaw piece puzzle"],
      ["🧸","teddy bear","bear teddy"],
      ["🪅","pinata","pinata"],
      ["🪆","nesting dolls","dolls nesting"],
      ["♠️","black spade suit","black spade spades suit"],
      ["♥️","black heart suit","black heart hearts suit"],
      ["♦️","black diamond suit","black diamond diamonds suit"],
      ["♣️","black club suit","black club clubs suit"],
      ["♟️","chess_pawn","chess chess_pawn pawn"],
      ["🃏","playing card black joker","black card joker playing"],
      ["🀄","mahjong tile red dragon","dragon mahjong red tile"],
      ["🎴","flower playing cards","cards flower playing"],
      ["🎭","performing arts","arts performing"],
      ["🖼️","frame_with_picture","frame frame_with_picture picture with"],
      ["🎨","artist palette","art artist palette"],
      ["🧵","spool of thread","of spool thread"],
      ["🪡","sewing needle","needle sewing"],
      ["🧶","ball of yarn","ball of yarn"],
      ["🪢","knot","knot"],
    ]
  },
  {
    "name": "Objects",
    "label": "Objects",
    "tab": "\ud83d\udca1",
    "emojis": [
      ["👓","eyeglasses","eyeglasses"],
      ["🕶️","dark_sunglasses","dark dark_sunglasses sunglasses"],
      ["🥽","goggles","goggles"],
      ["🥼","lab coat","coat lab"],
      ["🦺","safety vest","safety vest"],
      ["👔","necktie","necktie"],
      ["👕","t-shirt","shirt t tshirt"],
      ["👖","jeans","jeans"],
      ["🧣","scarf","scarf"],
      ["🧤","gloves","gloves"],
      ["🧥","coat","coat"],
      ["🧦","socks","socks"],
      ["👗","dress","dress"],
      ["👘","kimono","kimono"],
      ["🥻","sari","sari"],
      ["🩱","one-piece swimsuit","one piece swimsuit"],
      ["🩲","briefs","briefs"],
      ["🩳","shorts","shorts"],
      ["👙","bikini","bikini"],
      ["👚","womans clothes","clothes womans"],
      ["👛","purse","purse"],
      ["👜","handbag","handbag"],
      ["👝","pouch","pouch"],
      ["🛍️","shopping_bags","bags shopping shopping_bags"],
      ["🎒","school satchel","satchel school"],
      ["🩴","thong sandal","sandal thong"],
      ["👞","mans shoe","mans shoe"],
      ["👟","athletic shoe","athletic shoe"],
      ["🥾","hiking boot","boot hiking"],
      ["🥿","flat shoe","flat shoe womans"],
      ["👠","high-heeled shoe","heel heeled high shoe"],
      ["👡","womans sandal","sandal womans"],
      ["🩰","ballet shoes","ballet shoes"],
      ["👢","womans boots","boot boots womans"],
      ["👑","crown","crown"],
      ["👒","womans hat","hat womans"],
      ["🎩","top hat","hat top tophat"],
      ["🎓","graduation cap","board cap graduation mortar"],
      ["🧢","billed cap","billed cap"],
      ["🪖","military helmet","helmet military"],
      ["⛑️","helmet_with_white_cross","cross helmet helmet_with_white_cross white with"],
      ["📿","prayer beads","beads prayer"],
      ["💄","lipstick","lipstick"],
      ["💍","ring","ring"],
      ["💎","gem stone","gem stone"],
      ["🔇","speaker with cancellation stroke","cancellation mute speaker stroke with"],
      ["🔈","speaker","speaker"],
      ["🔉","speaker with one sound wave","one sound speaker wave with"],
      ["🔊","speaker with three sound waves","loud sound speaker three waves with"],
      ["📢","public address loudspeaker","address loudspeaker public"],
      ["📣","cheering megaphone","cheering mega megaphone"],
      ["📯","postal horn","horn postal"],
      ["🔔","bell","bell"],
      ["🔕","bell with cancellation stroke","bell cancellation no stroke with"],
      ["🎼","musical score","musical score"],
      ["🎵","musical note","musical note"],
      ["🎶","multiple musical notes","multiple musical notes"],
      ["🎙️","studio_microphone","microphone studio studio_microphone"],
      ["🎚️","level_slider","level level_slider slider"],
      ["🎛️","control_knobs","control control_knobs knobs"],
      ["🎤","microphone","microphone"],
      ["🎧","headphone","headphone headphones"],
      ["📻","radio","radio"],
      ["🎷","saxophone","saxophone"],
      ["🪗","accordion","accordion"],
      ["🎸","guitar","guitar"],
      ["🎹","musical keyboard","keyboard musical"],
      ["🎺","trumpet","trumpet"],
      ["🎻","violin","violin"],
      ["🪕","banjo","banjo"],
      ["🥁","drum with drumsticks","drum drumsticks with"],
      ["🪘","long drum","drum long"],
      ["📱","mobile phone","iphone mobile phone"],
      ["📲","mobile phone with rightwards arrow at left","arrow at calling left mobile phone rightwards with"],
      ["☎️","black telephone","black phone telephone"],
      ["📞","telephone receiver","receiver telephone"],
      ["📟","pager","pager"],
      ["📠","fax machine","fax machine"],
      ["🔋","battery","battery"],
      ["🔌","electric plug","electric plug"],
      ["💻","personal computer","computer personal"],
      ["🖥️","desktop_computer","computer desktop desktop_computer"],
      ["🖨️","printer","printer"],
      ["⌨️","keyboard","keyboard"],
      ["🖱️","three_button_mouse","button mouse three three_button_mouse"],
      ["🖲️","trackball","trackball"],
      ["💽","minidisc","minidisc"],
      ["💾","floppy disk","disk floppy"],
      ["💿","optical disc","cd disc optical"],
      ["📀","dvd","dvd"],
      ["🧮","abacus","abacus"],
      ["🎥","movie camera","camera movie"],
      ["🎞️","film_frames","film film_frames frames"],
      ["📽️","film_projector","film film_projector projector"],
      ["🎬","clapper board","board clapper"],
      ["📺","television","television tv"],
      ["📷","camera","camera"],
      ["📸","camera with flash","camera flash with"],
      ["📹","video camera","camera video"],
      ["📼","videocassette","vhs videocassette"],
      ["🔍","left-pointing magnifying glass","glass left mag magnifying pointing"],
      ["🔎","right-pointing magnifying glass","glass mag magnifying pointing right"],
      ["🕯️","candle","candle"],
      ["💡","electric light bulb","bulb electric light"],
      ["🔦","electric torch","electric flashlight torch"],
      ["🏮","izakaya lantern","izakaya lantern"],
      ["🪔","diya lamp","diya lamp"],
      ["📔","notebook with decorative cover","cover decorative notebook with"],
      ["📕","closed book","book closed"],
      ["📖","open book","book open"],
      ["📗","green book","book green"],
      ["📘","blue book","blue book"],
      ["📙","orange book","book orange"],
      ["📚","books","books"],
      ["📓","notebook","notebook"],
      ["📒","ledger","ledger"],
      ["📃","page with curl","curl page with"],
      ["📜","scroll","scroll"],
      ["📄","page facing up","facing page up"],
      ["📰","newspaper","newspaper"],
      ["🗞️","rolled_up_newspaper","newspaper rolled rolled_up_newspaper up"],
      ["📑","bookmark tabs","bookmark tabs"],
      ["🔖","bookmark","bookmark"],
      ["🏷️","label","label"],
      ["💰","money bag","bag money moneybag"],
      ["🪙","coin","coin"],
      ["💴","banknote with yen sign","banknote sign with yen"],
      ["💵","banknote with dollar sign","banknote dollar sign with"],
      ["💶","banknote with euro sign","banknote euro sign with"],
      ["💷","banknote with pound sign","banknote pound sign with"],
      ["💸","money with wings","money wings with"],
      ["💳","credit card","card credit"],
      ["🧾","receipt","receipt"],
      ["💹","chart with upwards trend and yen sign","and chart sign trend upwards with yen"],
      ["✉️","envelope","email envelope"],
      ["📧","e-mail symbol","e mail symbol"],
      ["📨","incoming envelope","envelope incoming"],
      ["📩","envelope with downwards arrow above","above arrow downwards envelope with"],
      ["📤","outbox tray","outbox tray"],
      ["📥","inbox tray","inbox tray"],
      ["📦","package","package"],
      ["📫","closed mailbox with raised flag","closed flag mailbox raised with"],
      ["📪","closed mailbox with lowered flag","closed flag lowered mailbox with"],
      ["📬","open mailbox with raised flag","flag mail mailbox open raised with"],
      ["📭","open mailbox with lowered flag","flag lowered mail mailbox no open with"],
      ["📮","postbox","postbox"],
      ["🗳️","ballot_box_with_ballot","ballot ballot_box_with_ballot box with"],
      ["✏️","pencil","pencil pencil2"],
      ["✒️","black nib","black nib"],
      ["🖋️","lower_left_fountain_pen","fountain left lower lower_left_fountain_pen pen"],
      ["🖊️","lower_left_ballpoint_pen","ballpoint left lower lower_left_ballpoint_pen pen"],
      ["🖌️","lower_left_paintbrush","left lower lower_left_paintbrush paintbrush"],
      ["🖍️","lower_left_crayon","crayon left lower lower_left_crayon"],
      ["📝","memo","memo pencil"],
      ["💼","briefcase","briefcase"],
      ["📁","file folder","file folder"],
      ["📂","open file folder","file folder open"],
      ["🗂️","card_index_dividers","card card_index_dividers dividers index"],
      ["📅","calendar","calendar date"],
      ["📆","tear-off calendar","calendar off tear"],
      ["🗒️","spiral_note_pad","note pad spiral spiral_note_pad"],
      ["🗓️","spiral_calendar_pad","calendar pad spiral spiral_calendar_pad"],
      ["📇","card index","card index"],
      ["📈","chart with upwards trend","chart trend upwards with"],
      ["📉","chart with downwards trend","chart downwards trend with"],
      ["📊","bar chart","bar chart"],
      ["📋","clipboard","clipboard"],
      ["📌","pushpin","pushpin"],
      ["📍","round pushpin","pushpin round"],
      ["📎","paperclip","paperclip"],
      ["🖇️","linked_paperclips","linked linked_paperclips paperclips"],
      ["📏","straight ruler","ruler straight"],
      ["📐","triangular ruler","ruler triangular"],
      ["✂️","black scissors","black scissors"],
      ["🗃️","card_file_box","box card card_file_box file"],
      ["🗄️","file_cabinet","cabinet file file_cabinet"],
      ["🗑️","wastebasket","wastebasket"],
      ["🔒","lock","lock"],
      ["🔓","open lock","lock open unlock"],
      ["🔏","lock with ink pen","ink lock pen with"],
      ["🔐","closed lock with key","closed key lock with"],
      ["🔑","key","key"],
      ["🗝️","old_key","key old old_key"],
      ["🔨","hammer","hammer"],
      ["🪓","axe","axe"],
      ["⛏️","pick","pick"],
      ["⚒️","hammer_and_pick","and hammer hammer_and_pick pick"],
      ["🛠️","hammer_and_wrench","and hammer hammer_and_wrench wrench"],
      ["🗡️","dagger_knife","dagger dagger_knife knife"],
      ["⚔️","crossed_swords","crossed crossed_swords swords"],
      ["🔫","pistol","gun pistol"],
      ["🪃","boomerang","boomerang"],
      ["🏹","bow and arrow","and arrow bow"],
      ["🛡️","shield","shield"],
      ["🪚","carpentry saw","carpentry saw"],
      ["🔧","wrench","wrench"],
      ["🪛","screwdriver","screwdriver"],
      ["🔩","nut and bolt","and bolt nut"],
      ["⚙️","gear","gear"],
      ["🗜️","compression","compression"],
      ["⚖️","scales","scales"],
      ["🦯","probing cane","cane probing"],
      ["🔗","link symbol","link symbol"],
      ["⛓️","chains","chains"],
      ["🪝","hook","hook"],
      ["🧰","toolbox","toolbox"],
      ["🧲","magnet","magnet"],
      ["🪜","ladder","ladder"],
      ["⚗️","alembic","alembic"],
      ["🧪","test tube","test tube"],
      ["🧫","petri dish","dish petri"],
      ["🧬","dna double helix","dna double helix"],
      ["🔬","microscope","microscope"],
      ["🔭","telescope","telescope"],
      ["📡","satellite antenna","antenna satellite"],
      ["💉","syringe","syringe"],
      ["🩸","drop of blood","blood drop of"],
      ["💊","pill","pill"],
      ["🩹","adhesive bandage","adhesive bandage"],
      ["🩺","stethoscope","stethoscope"],
      ["🚪","door","door"],
      ["🛗","elevator","elevator"],
      ["🪞","mirror","mirror"],
      ["🪟","window","window"],
      ["🛏️","bed","bed"],
      ["🛋️","couch_and_lamp","and couch couch_and_lamp lamp"],
      ["🪑","chair","chair"],
      ["🚽","toilet","toilet"],
      ["🪠","plunger","plunger"],
      ["🚿","shower","shower"],
      ["🛁","bathtub","bathtub"],
      ["🪤","mouse trap","mouse trap"],
      ["🪒","razor","razor"],
      ["🧴","lotion bottle","bottle lotion"],
      ["🧷","safety pin","pin safety"],
      ["🧹","broom","broom"],
      ["🧺","basket","basket"],
      ["🧻","roll of paper","of paper roll"],
      ["🪣","bucket","bucket"],
      ["🧼","bar of soap","bar of soap"],
      ["🪥","toothbrush","toothbrush"],
      ["🧽","sponge","sponge"],
      ["🧯","fire extinguisher","extinguisher fire"],
      ["🛒","shopping trolley","shopping trolley"],
      ["🚬","smoking symbol","smoking symbol"],
      ["⚰️","coffin","coffin"],
      ["🪦","headstone","headstone"],
      ["⚱️","funeral_urn","funeral funeral_urn urn"],
      ["🗿","moyai","moyai"],
      ["🪧","placard","placard"],
    ]
  },
  {
    "name": "Symbols",
    "label": "Symbols",
    "tab": "\u2764\ufe0f",
    "emojis": [
      ["🏧","automated teller machine","atm automated machine teller"],
      ["🚮","put litter in its place symbol","in its litter place put symbol"],
      ["🚰","potable water symbol","potable symbol water"],
      ["♿","wheelchair symbol","symbol wheelchair"],
      ["🚹","mens symbol","mens symbol"],
      ["🚺","womens symbol","symbol womens"],
      ["🚻","restroom","restroom"],
      ["🚼","baby symbol","baby symbol"],
      ["🚾","water closet","closet water wc"],
      ["🛂","passport control","control passport"],
      ["🛃","customs","customs"],
      ["🛄","baggage claim","baggage claim"],
      ["🛅","left luggage","left luggage"],
      ["⚠️","warning sign","sign warning"],
      ["🚸","children crossing","children crossing"],
      ["⛔","no entry","entry no"],
      ["🚫","no entry sign","entry no sign"],
      ["🚳","no bicycles","bicycles no"],
      ["🚭","no smoking symbol","no smoking symbol"],
      ["🚯","do not litter symbol","do litter not symbol"],
      ["🚱","non-potable water symbol","non potable symbol water"],
      ["🚷","no pedestrians","no pedestrians"],
      ["📵","no mobile phones","mobile no phones"],
      ["🔞","no one under eighteen symbol","eighteen no one symbol under underage"],
      ["☢️","radioactive_sign","radioactive radioactive_sign sign"],
      ["☣️","biohazard_sign","biohazard biohazard_sign sign"],
      ["⬆️","upwards black arrow","arrow black up upwards"],
      ["↗️","north east arrow","arrow east north right upper"],
      ["➡️","black rightwards arrow","arrow black right rightwards"],
      ["↘️","south east arrow","arrow east lower right south"],
      ["⬇️","downwards black arrow","arrow black down downwards"],
      ["↙️","south west arrow","arrow left lower south west"],
      ["⬅️","leftwards black arrow","arrow black left leftwards"],
      ["↖️","north west arrow","arrow left north upper west"],
      ["↕️","up down arrow","arrow down up"],
      ["↔️","left right arrow","arrow left right"],
      ["↩️","leftwards arrow with hook","arrow hook leftwards with"],
      ["↪️","rightwards arrow with hook","arrow hook right rightwards with"],
      ["⤴️","arrow pointing rightwards then curving upwards","arrow curving heading pointing rightwards then up upwards"],
      ["⤵️","arrow pointing rightwards then curving downwards","arrow curving down downwards heading pointing rightwards then"],
      ["🔃","clockwise downwards and upwards open circle arrows","and arrows circle clockwise downwards open upwards"],
      ["🔄","anticlockwise downwards and upwards open circle arrows","and anticlockwise arrows circle counterclockwise downwards open upwards"],
      ["🔙","back with leftwards arrow above","above arrow back leftwards with"],
      ["🔚","end with leftwards arrow above","above arrow end leftwards with"],
      ["🔛","on with exclamation mark with left right arrow above","above arrow exclamation left mark on right with"],
      ["🔜","soon with rightwards arrow above","above arrow rightwards soon with"],
      ["🔝","top with upwards arrow above","above arrow top upwards with"],
      ["🛐","place of worship","of place worship"],
      ["⚛️","atom_symbol","atom atom_symbol symbol"],
      ["🕉️","om_symbol","om om_symbol symbol"],
      ["✡️","star_of_david","david of star star_of_david"],
      ["☸️","wheel_of_dharma","dharma of wheel wheel_of_dharma"],
      ["☯️","yin_yang","yang yin yin_yang"],
      ["✝️","latin_cross","cross latin latin_cross"],
      ["☦️","orthodox_cross","cross orthodox orthodox_cross"],
      ["☪️","star_and_crescent","and crescent star star_and_crescent"],
      ["☮️","peace_symbol","peace peace_symbol symbol"],
      ["🕎","menorah with nine branches","branches menorah nine with"],
      ["🔯","six pointed star with middle dot","dot middle pointed six star with"],
      ["♈","aries","aries"],
      ["♉","taurus","taurus"],
      ["♊","gemini","gemini"],
      ["♋","cancer","cancer"],
      ["♌","leo","leo"],
      ["♍","virgo","virgo"],
      ["♎","libra","libra"],
      ["♏","scorpius","scorpius"],
      ["♐","sagittarius","sagittarius"],
      ["♑","capricorn","capricorn"],
      ["♒","aquarius","aquarius"],
      ["♓","pisces","pisces"],
      ["⛎","ophiuchus","ophiuchus"],
      ["🔀","twisted rightwards arrows","arrows rightwards twisted"],
      ["🔁","clockwise rightwards and leftwards open circle arrows","and arrows circle clockwise leftwards open repeat rightwards"],
      ["🔂","clockwise rightwards and leftwards open circle arrows with circled one overlay","and arrows circle circled clockwise leftwards one open overlay repeat rightwards with"],
      ["▶️","black right-pointing triangle","arrow black forward pointing right triangle"],
      ["⏩","black right-pointing double triangle","black double fast forward pointing right triangle"],
      ["⏭️","black_right_pointing_double_triangle_with_vertical_bar","bar black black_right_pointing_double_triangle_with_vertical_bar double pointing right triangle vertical with"],
      ["⏯️","black_right_pointing_triangle_with_double_vertical_bar","bar black black_right_pointing_triangle_with_double_vertical_bar double pointing right triangle vertical with"],
      ["◀️","black left-pointing triangle","arrow backward black left pointing triangle"],
      ["⏪","black left-pointing double triangle","black double left pointing rewind triangle"],
      ["⏮️","black_left_pointing_double_triangle_with_vertical_bar","bar black black_left_pointing_double_triangle_with_vertical_bar double left pointing triangle vertical with"],
      ["🔼","up-pointing small red triangle","arrow pointing red small triangle up"],
      ["⏫","black up-pointing double triangle","arrow black double pointing triangle up"],
      ["🔽","down-pointing small red triangle","arrow down pointing red small triangle"],
      ["⏬","black down-pointing double triangle","arrow black double down pointing triangle"],
      ["⏸️","double_vertical_bar","bar double double_vertical_bar vertical"],
      ["⏹️","black_square_for_stop","black black_square_for_stop for square stop"],
      ["⏺️","black_circle_for_record","black black_circle_for_record circle for record"],
      ["⏏️","eject","eject"],
      ["🎦","cinema","cinema"],
      ["🔅","low brightness symbol","brightness low symbol"],
      ["🔆","high brightness symbol","brightness high symbol"],
      ["📶","antenna with bars","antenna bars signal strength with"],
      ["📳","vibration mode","mode vibration"],
      ["📴","mobile phone off","mobile off phone"],
      ["♀️","female_sign","female female_sign sign"],
      ["♂️","male_sign","male male_sign sign"],
      ["⚧️","transgender_symbol","symbol transgender transgender_symbol"],
      ["✖️","heavy multiplication x","heavy multiplication x"],
      ["➕","heavy plus sign","heavy plus sign"],
      ["➖","heavy minus sign","heavy minus sign"],
      ["➗","heavy division sign","division heavy sign"],
      ["♾️","infinity","infinity"],
      ["‼️","double exclamation mark","bangbang double exclamation mark"],
      ["⁉️","exclamation question mark","exclamation interrobang mark question"],
      ["❓","black question mark ornament","black mark ornament question"],
      ["❔","white question mark ornament","grey mark ornament question white"],
      ["❕","white exclamation mark ornament","exclamation grey mark ornament white"],
      ["❗","heavy exclamation mark symbol","exclamation heavy mark symbol"],
      ["〰️","wavy dash","dash wavy"],
      ["💱","currency exchange","currency exchange"],
      ["💲","heavy dollar sign","dollar heavy sign"],
      ["⚕️","medical_symbol","aesculapius medical medical_symbol of staff symbol"],
      ["♻️","black universal recycling symbol","black recycle recycling symbol universal"],
      ["⚜️","fleur_de_lis","de fleur fleur_de_lis lis"],
      ["🔱","trident emblem","emblem trident"],
      ["📛","name badge","badge name"],
      ["🔰","japanese symbol for beginner","beginner for japanese symbol"],
      ["⭕","heavy large circle","circle heavy large o"],
      ["✅","white heavy check mark","check heavy mark white"],
      ["☑️","ballot box with check","ballot box check with"],
      ["✔️","heavy check mark","check heavy mark"],
      ["❌","cross mark","cross mark x"],
      ["❎","negative squared cross mark","cross mark negative squared"],
      ["➰","curly loop","curly loop"],
      ["➿","double curly loop","curly double loop"],
      ["〽️","part alternation mark","alternation mark part"],
      ["✳️","eight spoked asterisk","asterisk eight spoked"],
      ["✴️","eight pointed black star","black eight pointed star"],
      ["❇️","sparkle","sparkle"],
      ["©️","copyright sign","copyright sign"],
      ["®️","registered sign","registered sign"],
      ["™️","trade mark sign","mark sign tm trade"],
      ["#️⃣","hash key","hash key"],
      ["*️⃣","keycap_star","keycap keycap_star star"],
      ["0️⃣","keycap 0","0 keycap zero"],
      ["1️⃣","keycap 1","1 keycap one"],
      ["2️⃣","keycap 2","2 keycap two"],
      ["3️⃣","keycap 3","3 keycap three"],
      ["4️⃣","keycap 4","4 four keycap"],
      ["5️⃣","keycap 5","5 five keycap"],
      ["6️⃣","keycap 6","6 keycap six"],
      ["7️⃣","keycap 7","7 keycap seven"],
      ["8️⃣","keycap 8","8 eight keycap"],
      ["9️⃣","keycap 9","9 keycap nine"],
      ["🔟","keycap ten","keycap ten"],
      ["🔠","input symbol for latin capital letters","abcd capital for input latin letters symbol"],
      ["🔡","input symbol for latin small letters","abcd for input latin letters small symbol"],
      ["🔢","input symbol for numbers","1234 for input numbers symbol"],
      ["🔣","input symbol for symbols","for input symbol symbols"],
      ["🔤","input symbol for latin letters","abc for input latin letters symbol"],
      ["🅰️","negative squared latin capital letter a","a capital latin letter negative squared"],
      ["🆎","negative squared ab","ab negative squared"],
      ["🅱️","negative squared latin capital letter b","b capital latin letter negative squared"],
      ["🆑","squared cl","cl squared"],
      ["🆒","squared cool","cool squared"],
      ["🆓","squared free","free squared"],
      ["ℹ️","information source","information source"],
      ["🆔","squared id","id squared"],
      ["Ⓜ️","circled latin capital letter m","capital circled latin letter m"],
      ["🆕","squared new","new squared"],
      ["🆖","squared ng","ng squared"],
      ["🅾️","negative squared latin capital letter o","capital latin letter negative o o2 squared"],
      ["🆗","squared ok","ok squared"],
      ["🅿️","negative squared latin capital letter p","capital latin letter negative p parking squared"],
      ["🆘","squared sos","sos squared"],
      ["🆙","squared up with exclamation mark","exclamation mark squared up with"],
      ["🆚","squared vs","squared vs"],
      ["🈁","squared katakana koko","katakana koko squared"],
      ["🈂️","squared katakana sa","katakana sa squared"],
      ["🈷️","squared cjk unified ideograph-6708","6708 cjk ideograph squared u6708 unified"],
      ["🈶","squared cjk unified ideograph-6709","6709 cjk ideograph squared u6709 unified"],
      ["🈯","squared cjk unified ideograph-6307","6307 cjk ideograph squared u6307 unified"],
      ["🉐","circled ideograph advantage","advantage circled ideograph"],
      ["🈹","squared cjk unified ideograph-5272","5272 cjk ideograph squared u5272 unified"],
      ["🈚","squared cjk unified ideograph-7121","7121 cjk ideograph squared u7121 unified"],
      ["🈲","squared cjk unified ideograph-7981","7981 cjk ideograph squared u7981 unified"],
      ["🉑","circled ideograph accept","accept circled ideograph"],
      ["🈸","squared cjk unified ideograph-7533","7533 cjk ideograph squared u7533 unified"],
      ["🈴","squared cjk unified ideograph-5408","5408 cjk ideograph squared u5408 unified"],
      ["🈳","squared cjk unified ideograph-7a7a","7a7a cjk ideograph squared u7a7a unified"],
      ["㊗️","circled ideograph congratulation","circled congratulation congratulations ideograph"],
      ["㊙️","circled ideograph secret","circled ideograph secret"],
      ["🈺","squared cjk unified ideograph-55b6","55b6 cjk ideograph squared u55b6 unified"],
      ["🈵","squared cjk unified ideograph-6e80","6e80 cjk ideograph squared u6e80 unified"],
      ["🔴","large red circle","circle large red"],
      ["🟠","large orange circle","circle large orange"],
      ["🟡","large yellow circle","circle large yellow"],
      ["🟢","large green circle","circle green large"],
      ["🔵","large blue circle","blue circle large"],
      ["🟣","large purple circle","circle large purple"],
      ["🟤","large brown circle","brown circle large"],
      ["⚫","medium black circle","black circle medium"],
      ["⚪","medium white circle","circle medium white"],
      ["🟥","large red square","large red square"],
      ["🟧","large orange square","large orange square"],
      ["🟨","large yellow square","large square yellow"],
      ["🟩","large green square","green large square"],
      ["🟦","large blue square","blue large square"],
      ["🟪","large purple square","large purple square"],
      ["🟫","large brown square","brown large square"],
      ["⬛","black large square","black large square"],
      ["⬜","white large square","large square white"],
      ["◼️","black medium square","black medium square"],
      ["◻️","white medium square","medium square white"],
      ["◾","black medium small square","black medium small square"],
      ["◽","white medium small square","medium small square white"],
      ["▪️","black small square","black small square"],
      ["▫️","white small square","small square white"],
      ["🔶","large orange diamond","diamond large orange"],
      ["🔷","large blue diamond","blue diamond large"],
      ["🔸","small orange diamond","diamond orange small"],
      ["🔹","small blue diamond","blue diamond small"],
      ["🔺","up-pointing red triangle","pointing red small triangle up"],
      ["🔻","down-pointing red triangle","down pointing red small triangle"],
      ["💠","diamond shape with a dot inside","a diamond dot inside shape with"],
      ["🔘","radio button","button radio"],
      ["🔳","white square button","button square white"],
      ["🔲","black square button","black button square"],
    ]
  },
  {
    "name": "Flags",
    "label": "Flags",
    "tab": "\ud83c\udff3\ufe0f",
    "emojis": [
      ["🏁","chequered flag","checkered chequered flag"],
      ["🚩","triangular flag on post","flag on post triangular"],
      ["🎌","crossed flags","crossed flags"],
      ["🏴","waving black flag","black flag waving"],
      ["🏳️","waving_white_flag","flag waving waving_white_flag white"],
      ["🏳️‍🌈","rainbow-flag","flag rainbow"],
      ["🏳️‍⚧️","transgender_flag","flag transgender transgender_flag"],
      ["🏴‍☠️","pirate_flag","flag pirate pirate_flag"],
      ["🇦🇨","ascension island flag","ac ascension flag island"],
      ["🇦🇩","andorra flag","ad andorra flag"],
      ["🇦🇪","united arab emirates flag","ae arab emirates flag united"],
      ["🇦🇫","afghanistan flag","af afghanistan flag"],
      ["🇦🇬","antigua & barbuda flag","& ag antigua barbuda flag"],
      ["🇦🇮","anguilla flag","ai anguilla flag"],
      ["🇦🇱","albania flag","al albania flag"],
      ["🇦🇲","armenia flag","am armenia flag"],
      ["🇦🇴","angola flag","angola ao flag"],
      ["🇦🇶","antarctica flag","antarctica aq flag"],
      ["🇦🇷","argentina flag","ar argentina flag"],
      ["🇦🇸","american samoa flag","american as flag samoa"],
      ["🇦🇹","austria flag","at austria flag"],
      ["🇦🇺","australia flag","au australia flag"],
      ["🇦🇼","aruba flag","aruba aw flag"],
      ["🇦🇽","åland islands flag","ax flag islands åland"],
      ["🇦🇿","azerbaijan flag","az azerbaijan flag"],
      ["🇧🇦","bosnia & herzegovina flag","& ba bosnia flag herzegovina"],
      ["🇧🇧","barbados flag","barbados bb flag"],
      ["🇧🇩","bangladesh flag","bangladesh bd flag"],
      ["🇧🇪","belgium flag","be belgium flag"],
      ["🇧🇫","burkina faso flag","bf burkina faso flag"],
      ["🇧🇬","bulgaria flag","bg bulgaria flag"],
      ["🇧🇭","bahrain flag","bahrain bh flag"],
      ["🇧🇮","burundi flag","bi burundi flag"],
      ["🇧🇯","benin flag","benin bj flag"],
      ["🇧🇱","st. barthélemy flag","barthélemy bl flag st."],
      ["🇧🇲","bermuda flag","bermuda bm flag"],
      ["🇧🇳","brunei flag","bn brunei flag"],
      ["🇧🇴","bolivia flag","bo bolivia flag"],
      ["🇧🇶","caribbean netherlands flag","bq caribbean flag netherlands"],
      ["🇧🇷","brazil flag","br brazil flag"],
      ["🇧🇸","bahamas flag","bahamas bs flag"],
      ["🇧🇹","bhutan flag","bhutan bt flag"],
      ["🇧🇻","bouvet island flag","bouvet bv flag island"],
      ["🇧🇼","botswana flag","botswana bw flag"],
      ["🇧🇾","belarus flag","belarus by flag"],
      ["🇧🇿","belize flag","belize bz flag"],
      ["🇨🇦","canada flag","ca canada flag"],
      ["🇨🇨","cocos (keeling) islands flag","(keeling) cc cocos flag islands"],
      ["🇨🇩","congo - kinshasa flag","cd congo flag kinshasa"],
      ["🇨🇫","central african republic flag","african central cf flag republic"],
      ["🇨🇬","congo - brazzaville flag","brazzaville cg congo flag"],
      ["🇨🇭","switzerland flag","ch flag switzerland"],
      ["🇨🇮","côte d’ivoire flag","ci côte d’ivoire flag"],
      ["🇨🇰","cook islands flag","ck cook flag islands"],
      ["🇨🇱","chile flag","chile cl flag"],
      ["🇨🇲","cameroon flag","cameroon cm flag"],
      ["🇨🇳","china flag","china cn flag"],
      ["🇨🇴","colombia flag","co colombia flag"],
      ["🇨🇵","clipperton island flag","clipperton cp flag island"],
      ["🇨🇷","costa rica flag","costa cr flag rica"],
      ["🇨🇺","cuba flag","cu cuba flag"],
      ["🇨🇻","cape verde flag","cape cv flag verde"],
      ["🇨🇼","curaçao flag","curaçao cw flag"],
      ["🇨🇽","christmas island flag","christmas cx flag island"],
      ["🇨🇾","cyprus flag","cy cyprus flag"],
      ["🇨🇿","czechia flag","cz czechia flag"],
      ["🇩🇪","germany flag","de flag germany"],
      ["🇩🇬","diego garcia flag","dg diego flag garcia"],
      ["🇩🇯","djibouti flag","dj djibouti flag"],
      ["🇩🇰","denmark flag","denmark dk flag"],
      ["🇩🇲","dominica flag","dm dominica flag"],
      ["🇩🇴","dominican republic flag","do dominican flag republic"],
      ["🇩🇿","algeria flag","algeria dz flag"],
      ["🇪🇦","ceuta & melilla flag","& ceuta ea flag melilla"],
      ["🇪🇨","ecuador flag","ec ecuador flag"],
      ["🇪🇪","estonia flag","ee estonia flag"],
      ["🇪🇬","egypt flag","eg egypt flag"],
      ["🇪🇭","western sahara flag","eh flag sahara western"],
      ["🇪🇷","eritrea flag","er eritrea flag"],
      ["🇪🇸","spain flag","es flag spain"],
      ["🇪🇹","ethiopia flag","et ethiopia flag"],
      ["🇪🇺","european union flag","eu european flag union"],
      ["🇫🇮","finland flag","fi finland flag"],
      ["🇫🇯","fiji flag","fiji fj flag"],
      ["🇫🇰","falkland islands flag","falkland fk flag islands"],
      ["🇫🇲","micronesia flag","flag fm micronesia"],
      ["🇫🇴","faroe islands flag","faroe flag fo islands"],
      ["🇫🇷","france flag","flag fr france"],
      ["🇬🇦","gabon flag","flag ga gabon"],
      ["🇬🇧","united kingdom flag","flag gb kingdom uk united"],
      ["🇬🇩","grenada flag","flag gd grenada"],
      ["🇬🇪","georgia flag","flag ge georgia"],
      ["🇬🇫","french guiana flag","flag french gf guiana"],
      ["🇬🇬","guernsey flag","flag gg guernsey"],
      ["🇬🇭","ghana flag","flag gh ghana"],
      ["🇬🇮","gibraltar flag","flag gi gibraltar"],
      ["🇬🇱","greenland flag","flag gl greenland"],
      ["🇬🇲","gambia flag","flag gambia gm"],
      ["🇬🇳","guinea flag","flag gn guinea"],
      ["🇬🇵","guadeloupe flag","flag gp guadeloupe"],
      ["🇬🇶","equatorial guinea flag","equatorial flag gq guinea"],
      ["🇬🇷","greece flag","flag gr greece"],
      ["🇬🇸","south georgia & south sandwich islands flag","& flag georgia gs islands sandwich south"],
      ["🇬🇹","guatemala flag","flag gt guatemala"],
      ["🇬🇺","guam flag","flag gu guam"],
      ["🇬🇼","guinea-bissau flag","bissau flag guinea gw"],
      ["🇬🇾","guyana flag","flag guyana gy"],
      ["🇭🇰","hong kong sar china flag","china flag hk hong kong sar"],
      ["🇭🇲","heard & mcdonald islands flag","& flag heard hm islands mcdonald"],
      ["🇭🇳","honduras flag","flag hn honduras"],
      ["🇭🇷","croatia flag","croatia flag hr"],
      ["🇭🇹","haiti flag","flag haiti ht"],
      ["🇭🇺","hungary flag","flag hu hungary"],
      ["🇮🇨","canary islands flag","canary flag ic islands"],
      ["🇮🇩","indonesia flag","flag id indonesia"],
      ["🇮🇪","ireland flag","flag ie ireland"],
      ["🇮🇱","israel flag","flag il israel"],
      ["🇮🇲","isle of man flag","flag im isle man of"],
      ["🇮🇳","india flag","flag in india"],
      ["🇮🇴","british indian ocean territory flag","british flag indian io ocean territory"],
      ["🇮🇶","iraq flag","flag iq iraq"],
      ["🇮🇷","iran flag","flag ir iran"],
      ["🇮🇸","iceland flag","flag iceland is"],
      ["🇮🇹","italy flag","flag it italy"],
      ["🇯🇪","jersey flag","flag je jersey"],
      ["🇯🇲","jamaica flag","flag jamaica jm"],
      ["🇯🇴","jordan flag","flag jo jordan"],
      ["🇯🇵","japan flag","flag japan jp"],
      ["🇰🇪","kenya flag","flag ke kenya"],
      ["🇰🇬","kyrgyzstan flag","flag kg kyrgyzstan"],
      ["🇰🇭","cambodia flag","cambodia flag kh"],
      ["🇰🇮","kiribati flag","flag ki kiribati"],
      ["🇰🇲","comoros flag","comoros flag km"],
      ["🇰🇳","st. kitts & nevis flag","& flag kitts kn nevis st."],
      ["🇰🇵","north korea flag","flag korea kp north"],
      ["🇰🇷","south korea flag","flag korea kr south"],
      ["🇰🇼","kuwait flag","flag kuwait kw"],
      ["🇰🇾","cayman islands flag","cayman flag islands ky"],
      ["🇰🇿","kazakhstan flag","flag kazakhstan kz"],
      ["🇱🇦","laos flag","flag la laos"],
      ["🇱🇧","lebanon flag","flag lb lebanon"],
      ["🇱🇨","st. lucia flag","flag lc lucia st."],
      ["🇱🇮","liechtenstein flag","flag li liechtenstein"],
      ["🇱🇰","sri lanka flag","flag lanka lk sri"],
      ["🇱🇷","liberia flag","flag liberia lr"],
      ["🇱🇸","lesotho flag","flag lesotho ls"],
      ["🇱🇹","lithuania flag","flag lithuania lt"],
      ["🇱🇺","luxembourg flag","flag lu luxembourg"],
      ["🇱🇻","latvia flag","flag latvia lv"],
      ["🇱🇾","libya flag","flag libya ly"],
      ["🇲🇦","morocco flag","flag ma morocco"],
      ["🇲🇨","monaco flag","flag mc monaco"],
      ["🇲🇩","moldova flag","flag md moldova"],
      ["🇲🇪","montenegro flag","flag me montenegro"],
      ["🇲🇫","st. martin flag","flag martin mf st."],
      ["🇲🇬","madagascar flag","flag madagascar mg"],
      ["🇲🇭","marshall islands flag","flag islands marshall mh"],
      ["🇲🇰","north macedonia flag","flag macedonia mk north"],
      ["🇲🇱","mali flag","flag mali ml"],
      ["🇲🇲","myanmar (burma) flag","(burma) flag mm myanmar"],
      ["🇲🇳","mongolia flag","flag mn mongolia"],
      ["🇲🇴","macao sar china flag","china flag macao mo sar"],
      ["🇲🇵","northern mariana islands flag","flag islands mariana mp northern"],
      ["🇲🇶","martinique flag","flag martinique mq"],
      ["🇲🇷","mauritania flag","flag mauritania mr"],
      ["🇲🇸","montserrat flag","flag montserrat ms"],
      ["🇲🇹","malta flag","flag malta mt"],
      ["🇲🇺","mauritius flag","flag mauritius mu"],
      ["🇲🇻","maldives flag","flag maldives mv"],
      ["🇲🇼","malawi flag","flag malawi mw"],
      ["🇲🇽","mexico flag","flag mexico mx"],
      ["🇲🇾","malaysia flag","flag malaysia my"],
      ["🇲🇿","mozambique flag","flag mozambique mz"],
      ["🇳🇦","namibia flag","flag na namibia"],
      ["🇳🇨","new caledonia flag","caledonia flag nc new"],
      ["🇳🇪","niger flag","flag ne niger"],
      ["🇳🇫","norfolk island flag","flag island nf norfolk"],
      ["🇳🇬","nigeria flag","flag ng nigeria"],
      ["🇳🇮","nicaragua flag","flag ni nicaragua"],
      ["🇳🇱","netherlands flag","flag netherlands nl"],
      ["🇳🇴","norway flag","flag no norway"],
      ["🇳🇵","nepal flag","flag nepal np"],
      ["🇳🇷","nauru flag","flag nauru nr"],
      ["🇳🇺","niue flag","flag niue nu"],
      ["🇳🇿","new zealand flag","flag new nz zealand"],
      ["🇴🇲","oman flag","flag om oman"],
      ["🇵🇦","panama flag","flag pa panama"],
      ["🇵🇪","peru flag","flag pe peru"],
      ["🇵🇫","french polynesia flag","flag french pf polynesia"],
      ["🇵🇬","papua new guinea flag","flag guinea new papua pg"],
      ["🇵🇭","philippines flag","flag ph philippines"],
      ["🇵🇰","pakistan flag","flag pakistan pk"],
      ["🇵🇱","poland flag","flag pl poland"],
      ["🇵🇲","st. pierre & miquelon flag","& flag miquelon pierre pm st."],
      ["🇵🇳","pitcairn islands flag","flag islands pitcairn pn"],
      ["🇵🇷","puerto rico flag","flag pr puerto rico"],
      ["🇵🇸","palestinian territories flag","flag palestinian ps territories"],
      ["🇵🇹","portugal flag","flag portugal pt"],
      ["🇵🇼","palau flag","flag palau pw"],
      ["🇵🇾","paraguay flag","flag paraguay py"],
      ["🇶🇦","qatar flag","flag qa qatar"],
      ["🇷🇪","réunion flag","flag re réunion"],
      ["🇷🇴","romania flag","flag ro romania"],
      ["🇷🇸","serbia flag","flag rs serbia"],
      ["🇷🇺","russia flag","flag ru russia"],
      ["🇷🇼","rwanda flag","flag rw rwanda"],
      ["🇸🇦","saudi arabia flag","arabia flag sa saudi"],
      ["🇸🇧","solomon islands flag","flag islands sb solomon"],
      ["🇸🇨","seychelles flag","flag sc seychelles"],
      ["🇸🇩","sudan flag","flag sd sudan"],
      ["🇸🇪","sweden flag","flag se sweden"],
      ["🇸🇬","singapore flag","flag sg singapore"],
      ["🇸🇭","st. helena flag","flag helena sh st."],
      ["🇸🇮","slovenia flag","flag si slovenia"],
      ["🇸🇯","svalbard & jan mayen flag","& flag jan mayen sj svalbard"],
      ["🇸🇰","slovakia flag","flag sk slovakia"],
      ["🇸🇱","sierra leone flag","flag leone sierra sl"],
      ["🇸🇲","san marino flag","flag marino san sm"],
      ["🇸🇳","senegal flag","flag senegal sn"],
      ["🇸🇴","somalia flag","flag so somalia"],
      ["🇸🇷","suriname flag","flag sr suriname"],
      ["🇸🇸","south sudan flag","flag south ss sudan"],
      ["🇸🇹","são tomé & príncipe flag","& flag príncipe st são tomé"],
      ["🇸🇻","el salvador flag","el flag salvador sv"],
      ["🇸🇽","sint maarten flag","flag maarten sint sx"],
      ["🇸🇾","syria flag","flag sy syria"],
      ["🇸🇿","eswatini flag","eswatini flag sz"],
      ["🇹🇦","tristan da cunha flag","cunha da flag ta tristan"],
      ["🇹🇨","turks & caicos islands flag","& caicos flag islands tc turks"],
      ["🇹🇩","chad flag","chad flag td"],
      ["🇹🇫","french southern territories flag","flag french southern territories tf"],
      ["🇹🇬","togo flag","flag tg togo"],
      ["🇹🇭","thailand flag","flag th thailand"],
      ["🇹🇯","tajikistan flag","flag tajikistan tj"],
      ["🇹🇰","tokelau flag","flag tk tokelau"],
      ["🇹🇱","timor-leste flag","flag leste timor tl"],
      ["🇹🇲","turkmenistan flag","flag tm turkmenistan"],
      ["🇹🇳","tunisia flag","flag tn tunisia"],
      ["🇹🇴","tonga flag","flag to tonga"],
      ["🇹🇷","turkey flag","flag tr turkey"],
      ["🇹🇹","trinidad & tobago flag","& flag tobago trinidad tt"],
      ["🇹🇻","tuvalu flag","flag tuvalu tv"],
      ["🇹🇼","taiwan flag","flag taiwan tw"],
      ["🇹🇿","tanzania flag","flag tanzania tz"],
      ["🇺🇦","ukraine flag","flag ua ukraine"],
      ["🇺🇬","uganda flag","flag ug uganda"],
      ["🇺🇲","u.s. outlying islands flag","flag islands outlying u.s. um"],
      ["🇺🇳","united nations flag","flag nations un united"],
      ["🇺🇸","united states flag","flag states united us"],
      ["🇺🇾","uruguay flag","flag uruguay uy"],
      ["🇺🇿","uzbekistan flag","flag uz uzbekistan"],
      ["🇻🇦","vatican city flag","city flag va vatican"],
      ["🇻🇨","st. vincent & grenadines flag","& flag grenadines st. vc vincent"],
      ["🇻🇪","venezuela flag","flag ve venezuela"],
      ["🇻🇬","british virgin islands flag","british flag islands vg virgin"],
      ["🇻🇮","u.s. virgin islands flag","flag islands u.s. vi virgin"],
      ["🇻🇳","vietnam flag","flag vietnam vn"],
      ["🇻🇺","vanuatu flag","flag vanuatu vu"],
      ["🇼🇫","wallis & futuna flag","& flag futuna wallis wf"],
      ["🇼🇸","samoa flag","flag samoa ws"],
      ["🇽🇰","kosovo flag","flag kosovo xk"],
      ["🇾🇪","yemen flag","flag ye yemen"],
      ["🇾🇹","mayotte flag","flag mayotte yt"],
      ["🇿🇦","south africa flag","africa flag south za"],
      ["🇿🇲","zambia flag","flag zambia zm"],
      ["🇿🇼","zimbabwe flag","flag zimbabwe zw"],
      ["🏴󠁧󠁢󠁥󠁮󠁧󠁿","england flag","england flag"],
      ["🏴󠁧󠁢󠁳󠁣󠁴󠁿","scotland flag","flag scotland"],
      ["🏴󠁧󠁢󠁷󠁬󠁳󠁿","wales flag","flag wales"],
    ]
  },
];
