format = """
(bg:#DA627D fg:#9A348E)\
${custom.project_pwd}\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$docker_context\
$deno\
$elixir\
$elm\
$erlang\
$golang\
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$php\
$python\
$conda\
$memory_usage\
$line_break$character"""

# Disable the blank line at the start of the prompt
add_newline = true

[custom.project_pwd]
when = "true"
command = "project_pwd.zsh"
format = "[  ](bg:#424868 fg:#7AA2F7)[$output ](italic bg:#424868 fg:#A8ABC0)"

[directory]
style = "bg:#313348 fg:#A8ABC0"
truncate_to_repo = true
truncation_length = 99
truncation_symbol = ""
read_only = " ◈ "
use_os_path_sep = true
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ""
style = "bg:#0e271d"
format = '[ $symbol $branch ]($style)'

[git_commit]
style = "bg:#0e271d"
format = '[󰕱 $hash$tag ]($style)'
only_detached = false

[git_status]
style = "bg:#0e271d"
format = '[$all_status$ahead_behind ]($style)'

[fill]
symbol = ' '

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[cmd_duration]
format = "[◄ $duration ](italic white)"

[deno]
symbol = " "
format = "[ ${symbol}deno ${version} ]($style)"
version_format = "${raw}"
style = "bold bg:#2ec4b6"

[lua]
symbol = " "
format = "[ ${symbol}lua ${version} ]($style)"
version_format = "${raw}"
style = "bold bg:#2b8fb9"

[nodejs]
symbol = " "
format = "[ ${symbol}node ${version} ]($style)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []
style = "bold bg:#3C873A"

[python]
symbol = " "
format = "[ ${symbol}py ${version} ]($style)"
version_format = "${raw}"
style = "bold bg:#3776AB"

[conda]
symbol = "◯ "
format = "[ $symbol$environment ]($style)"
style = "bold bg:#2aa198"

[docker_context]
symbol = "◧ "
format = "[ $symbol$context ]($style)"
style = "bold bg:#384d54"

[elixir]
symbol = " "
format = "[ ${symbol}ex ${version} OTP $otp_version ]($style)"
style = "bold bg:#6e4a7e"

[elm]
symbol = " "
format = "[ ${symbol}elm ${version} ]($style)"
style = "bold bg:#60B5CC"

[golang]
symbol = " "
format = "[ ${symbol}go ${version} ]($style)"
style = "bold bg:#00ADD8"

[java]
symbol = " "
format = "[ ${symbol}java ${version} ]($style)"
style = "bold bg:#f89820"

[kotlin]
symbol = " "
format = "[ ${symbol}kotlin ${version} ]($style)"
style = "bold bg:#7f52ff"

[gradle]
symbol = " "
format = "[ ${symbol}gradle ${version} ]($style)"
style = "bold bg:#023e8a"

[erlang]
symbol = " "
format = "[ ${symbol}erl ${version} ]($style)"
style = "bold bg:#B83998"

[php]
symbol = " "
format = "[ ${symbol}php ${version} ]($style)"
style = "bold bg:#787CB5"

[memory_usage]
symbol = "▪▫▪ "
format = " mem [${ram}( ${swap})]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[  ](bg:#444A68)'
error_symbol = '[  ](bg:color_red)'
