# ZSH config
export ZSH="$HOME/.oh-my-zsh"
HYPHEN_INSENSITIVE="true"
export UPDATE_ZSH_DAYS=14
HIST_STAMPS="yyyy-mm-dd"

# Oh-my-zsh config (add more in ~/.zsh/extra_config.zsh to avoid cluttering git diff)
plugins=(git fzf)

# Default editor in different environments (change in ~/.zsh/extra_config.zsh)
export SUDO_EDITOR=vim
export EDITOR=vim
export GUI_EDITOR=code

# My custom aliases and functions
source $HOME/.zsh/aliases.zsh

# Load custom configuration
if [[ -f ~/.zsh/extra_config.zsh ]]; then
  source ~/.zsh/extra_config.zsh
fi

source $ZSH/oh-my-zsh.sh
