#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --auto

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#exec dbus-launch --sh-syntax --exit-with-session i3 --shmlog-size 10000
#exec awesome
xrdb ~/.Xresources
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --addmode eDP1 1920x1080
sh ~/bin/desktop-environment.sh
/usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
