require("screens.info_screen")
require("screens.exit_screen")
require("screens.lock_screen")
require("screens.calc_screen")
require("screens.workstation")
require("screens.notification_screen")
require("screens.recorder_screen")
require("screens.timer")
