## PATHs
export JAVA_HOME="/usr/lib/jvm/java-14-openjdk"
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export GO111MODULE=on
export ANDROID_HOME=$HOME/Android/Sdk
export YARN_BIN=$HOME/.config/yarn/global/node_modules/.bin

export PATH="$PATH:$YARN_BIN:$JAVA_HOME/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$GOPATH:$HOME/bin:$GOBIN:$HOME/.gem/ruby/2.5.0/bin:$HOME/.gem/ruby/2.6.0/bin:/usr/lib/ruby/2.6.0:$HOME/.config/rofi/bin"

## Options section
setopt correct                                                  # Auto correct mistakes
setopt extendedglob                                             # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                                               # Case insensitive globbing
setopt rcexpandparam                                            # Array expension with parameters
setopt nocheckjobs                                              # Don't warn about running processes when exiting
setopt numericglobsort                                          # Sort filenames numerically when it makes sense
setopt nobeep                                                   # No beep
setopt appendhistory                                            # Immediately append history instead of overwriting
setopt histignorealldups                                        # If a new command is a duplicate, remove the older one
setopt autocd                                                   # if only directory path is entered, cd there.

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' rehash true                              # automatically find new executables in path
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
HISTFILE=~/.zhistory
HISTSIZE=100000
SAVEHIST=50000
export SUDO_EDITOR=/usr/bin/nvim
export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim
export REACT_EDITOR=/usr/bin/code

stty -ixon

WORDCHARS=${WORDCHARS//\/[&.;]}                                 # Don't consider certain characters part of the word

## Keybindings section
bindkey -e
bindkey '^[[7~' beginning-of-line                               # Home key
bindkey '^[[H' beginning-of-line                                # Home key
if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey "${terminfo[khome]}" beginning-of-line                # [Home] - Go to beginning of line
fi
bindkey '^[[8~' end-of-line                                     # End key
bindkey '^[[F' end-of-line                                     # End key
if [[ "${terminfo[kend]}" != "" ]]; then
  bindkey "${terminfo[kend]}" end-of-line                       # [End] - Go to end of line
fi
bindkey '^[[2~' overwrite-mode                                  # Insert key
bindkey '^[[3~' delete-char                                     # Delete key
bindkey '^[[C'  forward-char                                    # Right key
bindkey '^[[D'  backward-char                                   # Left key
bindkey '^[[5~' history-beginning-search-backward               # Page up key
bindkey '^[[6~' history-beginning-search-forward                # Page down key

# Navigate words with ctrl+arrow keys
bindkey '^[Oc' forward-word                                     #
bindkey '^[Od' backward-word                                    #
bindkey '^[[1;5D' backward-word                                 #
bindkey '^[[1;5C' forward-word                                  #
bindkey '^H' backward-kill-word                                 # delete previous word with ctrl+backspace
bindkey '^[[Z' undo                                             # Shift+tab undo last action

## Function sections
paclist() {
  # Source: https://bbs.archlinux.org/viewtopic.php?id=93683
  LC_ALL=C pacman -Qei $(pacman -Qu | cut -d " " -f 1) | \
    awk 'BEGIN {FS=":"} /^Name/{printf("\033[1;36m%s\033[1;37m", $2)} /^Description/{print $2}' | \
    less
}

## Alias section
alias du="ncdu --color dark -rr --exclude .git --exclude node_modules"
alias exa="exa -mhl --group-directories-first --git --time-style=long-iso"
alias cat="bat"
alias init-ping="ping 8.8.8.8 >> /tmp/ping-log &"
alias cp="cp -i"                                                # Confirm before overwriting something
alias df='df -h'                                                # Human-readable sizes
alias free='free -m'                                            # Show sizes in MB

alias ncmpc='ncmpc -p 6600 -h 127.0.0.1'

alias docker="sudo docker"
alias dc="sudo docker container"
alias dcls="dc ls --all"
alias dcrm="dc rm"
alias dcri="dc run --interactive --tty"
alias drun="sudo docker run"
alias dat="sudo docker attach"
alias ds="sudo docker start"

alias g='git'
alias gst='git status'
alias ga='git add'
alias gaa='git add --all'
alias gapa='git add --patch'
alias gau='git add --update'
alias gap='git apply'
alias gc='git commit -v'
alias gc!='git commit -v --amend'
alias gco='git checkout'
alias gd='git diff'
alias gdca='git diff --cached'
alias gdcw='git diff --cached --word-diff'
alias gdct='git describe --tags `git rev-list --tags --max-count=1`'
alias gdt='git diff-tree --no-commit-id --name-only -r'
alias gdw='git diff --word-diff'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbm='git rebase master'
alias grbs='git rebase --skip'
alias gm='git merge'
alias gma='git merge --abort'
alias gp='git push'
alias gl='git pull'
alias download='aria2c'
alias dl='aria2c -x 16'
alias got='go get'

if type nvim > /dev/null 2>&1; then
  alias vim='nvim'
fi

alias _='sudo'

# Theming section
autoload -U compinit colors zcalc
compinit -d
colors

# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# enable substitution for prompt
setopt prompt_subst

# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r

# Color ls and grep
if [ -x /usr/bin/dircolors ]; then
  # shellcheck disable=SC2015
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls="ls --color=auto"

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

forgit_log=fgl
forgit_diff=fgd
forgit_add=fga
forgit_reset_head=fgrh
forgit_ignore=fgi
forgit_restore=fgcf
forgit_clean=fgclean
forgit_stash_show=fgss

## sources
source /usr/share/nvm/init-nvm.sh

## Plugins section
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

source $HOME/.zsh.d/plugins/cdc/cdc.plugin.zsh
source $HOME/.zsh.d/plugins/zsh-ing/ing.plugin.zsh
source $HOME/.zsh.d/plugins/zsh-tab-title/title.plugin.zsh
source $HOME/.zsh.d/plugins/forgit/forgit.plugin.zsh
source $HOME/.zsh.d/plugins/autosrc/autosrc.zsh

source $HOME/.zsh.d/functions/general.zsh
source $HOME/.zsh.d/functions/hugo.zsh
source $HOME/.zsh.d/functions/git.zsh
source $HOME/.zsh.d/functions/npm.zsh
source $HOME/.zsh.d/functions/laptop.zsh
source $HOME/.zsh.d/functions/cd-reminder.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

## Plugin variables

# bind UP and DOWN arrow keys to history substring search
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

if $(ps -p$PPID| grep -q -e konsole -e qterminal); then
else
  # Use autosuggestion
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
  ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
fi

CDC_DIRS=$HOME/Documents/Projects

## Theme
source ~/.zsh.d/themes/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

precmd () { print -Pn "\e]0;/$(pwd | sed 's#.*/##') - ${USER}@${HOST%%.*}\a" }
title() { export TITLE="$*" }

###-tns-completion-start-###
if [ -f /home/mahdi/.tnsrc ]; then
    source /home/mahdi/.tnsrc
fi
###-tns-completion-end-###
